import 'server-only';
import {publicDatabase} from '@/shared/db/public';
import type {ApplicationUser} from '@/server/auth/application-user';
import {canonicalComplaint,type ComplaintCommand,type ComplaintFields,type ComplaintListItem,type ComplaintEvent,type ComplaintStatus,type Labels} from '@/features/complaints/model';
import {complaintCommandFingerprint,complaintFingerprint} from './fingerprint';
export type ComplaintDetail={reference:string;category_id:string;category_labels:Labels;location_id:string;location_labels:Labels;subject:string;description:string;location_clarification:string|null;status:ComplaintStatus;submitted_at:Date;updated_at:Date;status_changed_at:Date;revision:number;citizen_name?:string;citizen_email?:string;citizen_phone?:string|null};
const listItem=(row:Record<string,unknown>):ComplaintListItem=>({...row,submitted_at:new Date(row.submitted_at as string),updated_at:new Date(row.updated_at as string),revision:Number(row.revision)}) as ComplaintListItem;
const historyItem=(row:Record<string,unknown>):ComplaintEvent=>({...row,revision:Number(row.revision),occurred_at:new Date(row.occurred_at as string)}) as ComplaintEvent;
export async function submitComplaint(actor:ApplicationUser,input:ComplaintCommand){const sql=publicDatabase(),fields=canonicalComplaint(input),fingerprint=complaintFingerprint(input);const [result]=await sql`select * from app.submit_complaint(${actor.authUserId},${actor.providerSessionId},${actor.digest},${input.commandKey},${fingerprint},${fields.categoryId},${fields.locationId},${fields.subject},${fields.description},${fields.locationClarification},${input.confirmed})`;if(!result)throw new Error('Submission unconfirmed');return {reference:result.reference as string,replayed:Boolean(result.replayed)};}
export async function ownComplaint(actor:ApplicationUser,reference:string):Promise<ComplaintDetail|null>{const [row]=await publicDatabase()`select * from app.read_own_complaint(${actor.authUserId},${actor.providerSessionId},${actor.digest},${reference})`;return row?{...row,submitted_at:new Date(row.submitted_at),updated_at:new Date(row.updated_at),status_changed_at:new Date(row.status_changed_at),revision:Number(row.revision)} as ComplaintDetail:null;}
export async function listOwnComplaints(actor:ApplicationUser,query:{q?:string;status?:string;beforeTime?:string;beforeReference?:string},limit=20){const rows=await publicDatabase()`select * from app.list_own_complaints(${actor.authUserId},${actor.providerSessionId},${actor.digest},${query.q||null},${query.status||null},${query.beforeTime||null},${query.beforeReference||null},${limit})`;return rows.map(listItem);}
export async function ownComplaintHistory(actor:ApplicationUser,reference:string){return (await publicDatabase()`select * from app.read_own_complaint_history(${actor.authUserId},${actor.providerSessionId},${actor.digest},${reference},${50})`).map(historyItem);}
export async function listStaffComplaints(actor:ApplicationUser,query:{q?:string;status?:string;location?:string;beforeTime?:string;beforeReference?:string},limit=20){const rows=await publicDatabase()`select * from app.list_staff_complaints(${actor.authUserId},${actor.providerSessionId},${actor.digest},${query.q||null},${query.status||null},${query.location||null},${query.beforeTime||null},${query.beforeReference||null},${limit})`;return rows.map(listItem);}
export async function pageStaffComplaints(actor:ApplicationUser,query:{q?:string;status?:string;location?:string;page:number},limit=20){const rows=await publicDatabase()`select * from app.page_staff_complaints(${actor.authUserId},${actor.providerSessionId},${actor.digest},${query.q||null},${query.status||null},${query.location||null},${query.page},${limit})`;return {items:rows.map(listItem),totalCount:rows[0]?Number(rows[0].total_count):0};}
export async function staffComplaint(actor:ApplicationUser,reference:string):Promise<ComplaintDetail|null>{const [row]=await publicDatabase()`select * from app.read_staff_complaint(${actor.authUserId},${actor.providerSessionId},${actor.digest},${reference})`;return row?{...row,submitted_at:new Date(row.submitted_at),updated_at:new Date(row.updated_at),status_changed_at:new Date(row.status_changed_at),revision:Number(row.revision)} as ComplaintDetail:null;}
export async function staffComplaintHistory(actor:ApplicationUser,reference:string){return (await publicDatabase()`select * from app.read_staff_complaint_history(${actor.authUserId},${actor.providerSessionId},${actor.digest},${reference},${50})`).map(historyItem);}
export async function staffComplaintCounts(actor:ApplicationUser){const rows=await publicDatabase()`select * from app.staff_complaint_counts(${actor.authUserId},${actor.providerSessionId},${actor.digest})`;return Object.fromEntries(rows.map(row=>[row.status,Number(row.total)])) as Partial<Record<ComplaintStatus,number>>;}
export async function editOwnComplaint(actor:ApplicationUser,input:{reference:string;expectedRevision:number;commandKey:string}&ComplaintFields){const fields=canonicalComplaint(input),fingerprint=complaintCommandFingerprint('COMPLAINT_EDIT',{reference:input.reference,expectedRevision:input.expectedRevision,...fields});const [row]=await publicDatabase()`select * from app.edit_own_complaint(${actor.authUserId},${actor.providerSessionId},${actor.digest},${input.reference},${input.expectedRevision},${input.commandKey},${fingerprint},${fields.categoryId},${fields.locationId},${fields.subject},${fields.description},${fields.locationClarification})`;return row;}
export async function withdrawOwnComplaint(actor:ApplicationUser,input:{reference:string;expectedRevision:number;commandKey:string}){const value={reference:input.reference,expectedRevision:input.expectedRevision},fingerprint=complaintCommandFingerprint('COMPLAINT_WITHDRAW',value);const [row]=await publicDatabase()`select * from app.withdraw_own_complaint(${actor.authUserId},${actor.providerSessionId},${actor.digest},${input.reference},${input.expectedRevision},${input.commandKey},${fingerprint})`;return row;}
export async function startComplaintReview(actor:ApplicationUser,input:{reference:string;expectedRevision:number;commandKey:string}){const value={reference:input.reference,expectedRevision:input.expectedRevision},fingerprint=complaintCommandFingerprint('COMPLAINT_START_REVIEW',value);const [row]=await publicDatabase()`select * from app.start_complaint_review(${actor.authUserId},${actor.providerSessionId},${actor.digest},${input.reference},${input.expectedRevision},${input.commandKey},${fingerprint})`;return row;}
export async function recoverComplaint(actor:ApplicationUser,key:string):Promise<string|null>{const [row]=await publicDatabase()`select * from app.recover_complaint_command(${actor.authUserId},${actor.providerSessionId},${actor.digest},${key})`;return row?.reference??null;}
