import {randomUUID} from 'node:crypto';
import {notFound} from 'next/navigation';
import {requireCommuneStaff} from '@/server/auth/application-user';
import {staffComplaint,staffComplaintHistory} from '@/server/complaints/repository';
import {referencePattern} from '@/features/complaints/model';
import {ComplaintFacts} from '@/features/complaints/components/detail';
import {ComplaintTimeline,StatusBadge} from '@/features/complaints/components/tracking';
import {ConfirmAction} from '@/features/complaints/components/confirm-action';
import {startReviewAction} from '@/features/complaints/actions';
import {trackingCopy} from '@/features/complaints/tracking-copy';
import {Link} from '@/shared/i18n/navigation';
export const metadata={title:'Complaint detail',robots:{index:false,follow:false}};
export default async function Page({params,searchParams}:{params:Promise<{locale:'ar'|'fr'|'en';reference:string}>;searchParams:Promise<{state?:string}>}){const {locale,reference}=await params,actor=await requireCommuneStaff(locale,true);if(!referencePattern.test(reference))notFound();const [complaint,history,state]=await Promise.all([staffComplaint(actor,reference),staffComplaintHistory(actor,reference),searchParams]);if(!complaint)notFound();const c=trackingCopy[locale];return <section className="complaint-page commune-complaint"><span className="eyebrow">{c.inbox}</span><h1><bdi dir="ltr">{complaint.reference}</bdi></h1>{state.state&&<p className={`form-result ${state.state==='conflict'?'error':''}`} role="status">{state.state==='reviewing'?c.reviewing:state.state==='conflict'?c.conflict:''}</p>}<div className="complaint-panel"><StatusBadge locale={locale} status={complaint.status}/><ComplaintFacts locale={locale} values={complaint}/><p>{c.submitted}: <time dateTime={complaint.submitted_at.toISOString()}>{new Intl.DateTimeFormat(locale,{dateStyle:'long',timeStyle:'short',timeZone:'Africa/Casablanca'}).format(complaint.submitted_at)}</time></p><p>{c.updated}: <time dateTime={complaint.updated_at.toISOString()}>{new Intl.DateTimeFormat(locale,{dateStyle:'long',timeStyle:'short',timeZone:'Africa/Casablanca'}).format(complaint.updated_at)}</time></p></div><section className="commune-card complaint-contact"><h2>{c.contact}</h2><dl className="commune-details"><dt>{c.citizen}</dt><dd>{complaint.citizen_name}</dd><dt>{c.email}</dt><dd><bdi dir="ltr">{complaint.citizen_email}</bdi></dd><dt>{c.phone}</dt><dd><bdi dir="ltr">{complaint.citizen_phone??c.none}</bdi></dd></dl></section>{complaint.status==='SUBMITTED'&&<div className="complaint-actions"><ConfirmAction action={startReviewAction} title={c.startReview} message={c.reviewConfirm} cancel={c.cancel} danger={false} hidden={{locale,reference,expectedRevision:complaint.revision,commandKey:randomUUID()}}>{c.startReview}</ConfirmAction></div>}<ComplaintTimeline locale={locale} events={history}/><Link className="btn ghost" href="/commune/complaints">{c.inbox}</Link></section>;}
