import {requireCommuneStaff} from '@/server/auth/application-user';
import {pageStaffComplaints} from '@/server/complaints/repository';
import {readStaffLocationFilters} from '@/server/catalogues/repository';
import {complaintStatuses,catalogueLabel} from '@/features/complaints/model';
import {ComplaintList,ComplaintPagination} from '@/features/complaints/components/tracking';
import {statusLabel,trackingCopy} from '@/features/complaints/tracking-copy';
import {catalogueAdminCopy} from '@/features/catalogue-admin/copy';
import {inactiveOptionLabel} from '@/features/catalogue-admin/model';
export const metadata={title:'Complaints',robots:{index:false,follow:false}};
export default async function Page({params,searchParams}:{params:Promise<{locale:'ar'|'fr'|'en'}>;searchParams:Promise<Record<string,string|undefined>>}){const {locale}=await params,actor=await requireCommuneStaff(locale,true),raw=await searchParams,q=(raw.q??'').slice(0,150),status=complaintStatuses.includes(raw.status as never)?(raw.status??''):'',location=/^[0-9a-f-]{36}$/i.test(raw.location??'')?(raw.location??''):'',page=Math.min(Math.max(Number.parseInt(raw.page??'1',10)||1,1),10000),[{items,totalCount},locations]=await Promise.all([pageStaffComplaints(actor,{q,status,location,page}),readStaffLocationFilters(actor)]),c=trackingCopy[locale],inactive=catalogueAdminCopy[locale].inactive,pageCount=Math.max(1,Math.ceil(totalCount/20));const sorted=locations.sort((a,b)=>new Intl.Collator(locale).compare(catalogueLabel(a,locale).text,catalogueLabel(b,locale).text)||a.id.localeCompare(b.id));return <section className="tracking-page commune-tracking"><span className="eyebrow">{c.dashboard}</span><h1>{c.inbox}</h1><form className="tracking-filters"><label>{c.staffSearch}<input name="q" defaultValue={q}/></label><label>{c.filter}<select name="status" defaultValue={status}><option value="">{c.all}</option>{complaintStatuses.map(value=><option key={value} value={value}>{statusLabel(locale,value)}</option>)}</select></label><label>{c.location}<select name="location" defaultValue={location}><option value="">{c.all}</option>{sorted.map(item=>{const label=catalogueLabel(item,locale);return <option key={item.id} value={item.id} lang={label.language}>{item.isActive?label.text:inactiveOptionLabel(label.text,inactive)}</option>;})}</select></label><button className="btn" type="submit">{c.apply}</button></form>{items.length?<ComplaintList locale={locale} items={items} staff/>:<div className="tracking-empty">{q||status||location?c.noResults:c.empty}</div>}<ComplaintPagination locale={locale} page={Math.min(page,pageCount)} pageCount={pageCount} params={{q,status,location}}/></section>;}
