import {disposablePassword} from '../support/disposable-password';
import {expect,fillPassword} from '../support/private-password-input';
import AxeBuilder from '@axe-core/playwright';
import {test,type Page} from '@playwright/test';
import {randomUUID,createHash,randomBytes} from 'node:crypto';
import {localFixtureAuth} from '../support/local-fixtures';
import {join} from 'node:path';
import postgres from 'postgres';
import {bootstrapLocalStaff} from '../../scripts/local-staff';
import {localDatabaseUrl} from '../../scripts/local-target';
test.use({trace:'off',screenshot:'off',video:'off'});
const password=disposablePassword();
// Deliberately undersized input preserves the staff policy rejection test.
const invalidShortPassword=disposablePassword(13),changedPassword=disposablePassword(),recoveredPassword=disposablePassword();
const accounts={AGENT:`agent-${randomUUID()}@example.test`,ADMIN:`admin-${randomUUID()}@example.test`};
async function login(page:Page,email:string,pass=password,locale='en'){await page.goto(`/${locale}/commune/login`);await page.locator('input[name="email"]').fill(email);await fillPassword(page.locator('input[name="password"]'),pass);await page.locator('.commune-form button').click();}
test.describe.serial('Commune authentication and protected shell',()=>{
 test.setTimeout(90_000);
 test.beforeAll(async()=>{test.setTimeout(120_000);process.env.PATH=join(process.env.LOCALAPPDATA??'','Programs','Podman')+';'+process.env.PATH;process.env.DOCKER_HOST='npipe:////./pipe/podman-machine-default';for(const role of ['AGENT','ADMIN'] as const)await bootstrapLocalStaff({email:accounts[role],password,fullName:`Local ${role}`,role,language:'en'});});

 test('bootstrap is idempotent, rejects role conflicts and reconciles a marked interrupted fixture',async()=>{const result=await bootstrapLocalStaff({email:accounts.AGENT,password,fullName:'Local AGENT',role:'AGENT'});expect(result.created).toBe(false);await expect(bootstrapLocalStaff({email:accounts.AGENT,password,fullName:'Conflict',role:'ADMIN'})).rejects.toThrow('conflicting');const auth=localFixtureAuth(),email=`reconcile-${randomUUID()}@example.test`;const {data,error}=await auth.auth.admin.createUser({email,password,email_confirm:true,app_metadata:{local_staff_fixture:true,local_staff_role:'AGENT'}});expect(error).toBeNull();expect(data.user).toBeTruthy();expect((await bootstrapLocalStaff({email,password,fullName:'Reconciled fixture',role:'AGENT'})).created).toBe(true);});
 test('Citizen is denied Commune login and protected pages',async({page})=>{const auth=localFixtureAuth(),email=`citizen-staff-denial-${randomUUID()}@example.test`;const {data,error}=await auth.auth.admin.createUser({email,password,email_confirm:true});expect(error).toBeNull();const db=postgres(localDatabaseUrl(),{max:1});try{await db.begin(async tx=>{await tx`grant app_web to postgres`;await tx`set local role app_web`;const [legal]=await tx`select * from app.read_signup_legal('en')`;await tx`select * from app.provision_citizen(${data.user!.id},'Boundary Citizen',null,'en',${legal.terms_version_id},${legal.privacy_version_id})`;await tx`reset role`;await tx`revoke app_web from postgres`;});await expect(bootstrapLocalStaff({email,password,fullName:'Not promoted',role:'ADMIN'})).rejects.toThrow('conflicting');}finally{await db.end();}await login(page,email);await expect(page.locator('main').getByRole('alert')).toContainText('Unable');await page.goto('/en/login');await page.locator('[name="email"]').fill(email);await fillPassword(page.locator('[name="password"]'),password);await page.locator('button[type="submit"]').click();await expect(page).toHaveURL('/en/citizen');await page.goto('/en/commune/account');await expect(page).toHaveURL('/en/commune/access-denied');});
 test('unverified and provider-short staff passwords do not get application sessions',async({page})=>{test.setTimeout(180_000);const auth=localFixtureAuth(),db=postgres(localDatabaseUrl(),{max:1});try{for(const scenario of ['unverified','short']){const email=`${scenario}-${randomUUID()}@example.test`,pass=scenario==='short'?disposablePassword(10):password;const {data,error}=await auth.auth.admin.createUser({email,password:pass,email_confirm:scenario!=='unverified'});expect(error).toBeNull();await db`insert into app.application_profiles(auth_user_id,full_name,role,access_status) values(${data.user!.id},'Denied fixture','AGENT','ACTIVE')`;await login(page,email,pass);await expect(page.locator('main').getByRole('alert')).toContainText('Unable');const [count]=await db`select count(*)::int n from app.application_sessions where profile_id=(select id from app.application_profiles where auth_user_id=${data.user!.id})`;expect(count.n).toBe(0);}}finally{await db.end();}});
 test('expired application session is not recreated from a valid provider token',async({page})=>{await login(page,accounts.AGENT);await expect(page).toHaveURL('/en/commune');const cookie=(await page.context().cookies()).find(c=>c.name==='abaynou_app_session')!;const digest=createHash('sha256').update(cookie.value).digest(),db=postgres(localDatabaseUrl(),{max:1});try{const [session]=await db`select * from app.application_sessions where secret_digest=${digest}`;const expiredSecret=randomBytes(32).toString('base64url'),expiredDigest=createHash('sha256').update(expiredSecret).digest();await db.begin(async tx=>{await tx`alter table app.application_sessions disable trigger application_session_transition`;await tx`update app.application_sessions set started_at=now()-interval '9 hours',last_user_activity_at=now()-interval '9 hours',absolute_expires_at=now()-interval '1 hour',secret_digest=${expiredDigest} where id=${session.id}`;await tx`alter table app.application_sessions enable trigger application_session_transition`;});await page.context().addCookies([{...cookie,value:expiredSecret}]);await page.goto('/en/commune/login');await expect(page).toHaveURL('/en/commune/login');await expect(page.locator('input[name="email"]')).toBeVisible();await page.goto('/en/login');await expect(page).toHaveURL('/en/login');await expect(page.locator('input[name="email"]')).toBeVisible();await page.goto('/en/commune/account');await expect(page).toHaveURL('/en/commune/session-expired');await page.goto('/en/commune');await expect(page).toHaveURL('/en/commune/login');}finally{await db.end();}});

 for(const role of ['AGENT','ADMIN'] as const)test(`${role} sign in, own account, read-only identity and logout`,async({page})=>{
  await login(page,accounts[role]);await expect(page).toHaveURL('/en/commune');await expect(page.locator('.commune-identity')).toContainText(role==='ADMIN'?'Administrator':'Agent');await page.goto('/en/commune/account');await expect(page.locator('.commune-details')).toContainText(accounts[role]);await expect(page.locator('input[name="email"]')).toHaveCount(0);await expect(page.locator('select[name="role"]')).toHaveCount(0);await page.getByRole('button',{name:'Sign out'}).click();await expect(page).toHaveURL('/en/commune/login');await page.goto('/en/commune/account');await expect(page).toHaveURL(/\/en\/commune\/login$/);
 });
 for(const role of ['AGENT','ADMIN'] as const)test(`${role} active session skips login and footer opens own space`,async({page})=>{
  const stale=await page.context().newPage();await stale.goto('/en/login');await stale.locator('input[name="email"]').fill('other-citizen@example.test');await fillPassword(stale.locator('input[name="password"]'),disposablePassword());
  await login(page,accounts[role]);await expect(page).toHaveURL('/en/commune');
  const sessionBefore=(await page.context().cookies()).find(c=>c.name==='abaynou_app_session')?.value;await stale.locator('button[type="submit"]').click();await expect(stale).toHaveURL('/en/commune');expect((await page.context().cookies()).find(c=>c.name==='abaynou_app_session')?.value===sessionBefore).toBe(true);await stale.close();
  for(const locale of ['ar','fr','en']){for(const entry of ['login','commune/login','register']){await page.goto(`/${locale}/${entry}?returnTo=https://example.invalid`);await expect(page).toHaveURL(`/${locale}/commune`);}await page.goto(`/${locale}`);await expect(page).toHaveURL(`/${locale}`);await expect(page.locator('.head-actions a[href$="/citizen/account"]')).toHaveCount(0);await expect(page.locator('.public-header a[href$="/login"]')).toHaveCount(0);await expect(page.locator('.public-header a[href$="/register"]')).toHaveCount(0);await expect(page.locator('.head-actions .public-viewer-name')).toHaveText(`Local ${role}`);await page.locator('.head-actions .public-viewer-name').click();await expect(page).toHaveURL(`/${locale}/commune/account`);await page.goto(`/${locale}`);await page.locator('.commune-footer-link').click();await expect(page).toHaveURL(`/${locale}/commune`);}
  await page.goto('/en');await page.setViewportSize({width:390,height:844});await page.locator('.hamb').click();await expect(page.locator('.mobile-nav .public-viewer-name')).toHaveText(`Local ${role}`);await page.locator('.mobile-nav .public-viewer-name').click();await expect(page).toHaveURL('/en/commune/account');await page.goto('/en');await page.locator('.hamb').click();await page.locator('.mobile-nav form button').click();await expect(page).toHaveURL('/en/commune/login');await page.goto('/en');await expect(page.locator('.head-actions a[href="/en/login"]')).toHaveCount(1);await expect(page.locator('.commune-footer-link')).toBeVisible();
 });

 test('invalid password and staff Citizen entry both stay neutral',async({page})=>{await login(page,accounts.AGENT,disposablePassword());await expect(page.locator('main').getByRole('alert')).toContainText('Unable');await page.goto('/en/login');await page.locator('input[name="email"]').fill(accounts.AGENT);await fillPassword(page.locator('input[name="password"]'),password);await page.locator('button[type="submit"]').click();await expect(page.locator('main').getByRole('alert')).toContainText('Unable to sign in');await expect(page.locator('main a[href$="/commune/login"]')).toHaveCount(0);expect((await page.context().cookies()).some(c=>c.name==='abaynou_app_session')).toBe(false);await expect(page).not.toHaveURL(/complete-registration/);});
 test('staff cannot enter Citizen protected pages',async({page})=>{await login(page,accounts.AGENT);await expect(page).toHaveURL('/en/commune');for(const path of ['/citizen','/citizen/notifications','/citizen/account/email','/citizen/account/password','/complete-registration']){await page.goto('/en'+path);await expect(page).toHaveURL(/\/en\/commune(?:\/login)?$/);}});
 test('language changes the whole shell and mobile drawer supports Escape and focus',async({page})=>{await login(page,accounts.AGENT);await expect(page).toHaveURL('/en/commune');await page.goto('/en/commune/account');await page.locator('select[name="language"]').selectOption('ar');await page.locator('.commune-form button').click();await expect(page).toHaveURL('/ar/commune/account?state=saved');await expect(page.locator('html')).toHaveAttribute('dir','rtl');await page.setViewportSize({width:390,height:844});const menu=page.locator('.commune-menu');await menu.click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(menu).toBeFocused();await expect(page.getByRole('dialog')).toHaveCount(0);await menu.click();await expect(page.getByRole('dialog')).toBeVisible();await page.locator('.commune-backdrop').click({position:{x:10,y:400}});await expect(page.locator('.commune-sidebar')).toBeHidden();await expect(menu).toBeFocused();await page.emulateMedia({reducedMotion:'reduce'});await menu.click();expect(await page.locator('.commune-sidebar').evaluate(e=>getComputedStyle(e).transitionDuration)).toBe('0s');await page.keyboard.press('Escape');await page.locator('select[name="language"]').selectOption('fr');await page.locator('.commune-form button').click();await expect(page.locator('html')).toHaveAttribute('dir','ltr');await page.setViewportSize({width:320,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});

 for(const locale of ['ar','fr','en'])test(`Commune routes responsive and accessible in ${locale}`,async({page})=>{await login(page,accounts.AGENT,password,locale);await expect(page).toHaveURL(`/${locale}/commune`);for(const size of [{width:1440,height:1000},{width:820,height:1180},{width:390,height:844},{width:320,height:844}]){await page.setViewportSize(size);for(const path of ['','/account','/account/password']){await page.goto(`/${locale}/commune${path}`);await expect(page.locator('h1')).toHaveCount(1);await expect(page.locator('h1')).toBeVisible();await expect(page.locator('html')).toHaveAttribute('dir',locale==='ar'?'rtl':'ltr');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await page.locator('h1').evaluate(e=>getComputedStyle(e).fontFamily)).toContain('IBM Plex Sans Arabic');await page.screenshot({path:`test-results/commune/${locale}-${path.replaceAll('/','')||'home'}-${size.width}.png`,fullPage:true,mask:[page.locator('input[name*=assword],input[name=confirmation]')]});}}await page.setViewportSize({width:1440,height:1000});await page.goto(`/${locale}/commune/account`);await expect(page.locator('h1')).toBeVisible();expect((await new AxeBuilder({page}).analyze()).violations.map(({id})=>id)).toEqual([]);});

 test('password change enforces 15 characters and revokes another browser session',async({page,browser})=>{await login(page,accounts.ADMIN);await expect(page).toHaveURL('/en/commune');const second=await browser.newContext(),other=await second.newPage();await login(other,accounts.ADMIN);await expect(other).toHaveURL('/en/commune');await page.goto('/en/commune/account/password');await fillPassword(page.locator('[name="currentPassword"]'),password);await fillPassword(page.locator('[name="password"]'),invalidShortPassword);await fillPassword(page.locator('[name="confirmation"]'),invalidShortPassword);await page.locator('.commune-form button').click();await expect(page.locator('main').getByRole('alert')).toContainText('15 characters');await fillPassword(page.locator('[name="password"]'),changedPassword);await fillPassword(page.locator('[name="confirmation"]'),changedPassword);await page.locator('.commune-form button').click();await expect(page.getByRole('status')).toContainText('saved');await other.goto('/en/commune/account');await expect(other).toHaveURL(/\/commune\/session-expired$/);await second.close();});
 test('recovery GET is scanner safe and reset requires fresh login',async({page,request})=>{await page.goto('/en/commune/forgot-password');await page.locator('[name="email"]').fill(accounts.AGENT);await page.locator('.commune-form button').click();await expect(page.getByRole('status')).toContainText('If this address');let link='';for(let attempt=0;attempt<30&&!link;attempt++){const data=await (await request.get('http://127.0.0.1:54324/api/v1/messages')).json();for(const msg of data.messages??[]){if(!msg.To?.some((to:{Address:string})=>to.Address===accounts.AGENT))continue;const detail=await(await request.get(`http://127.0.0.1:54324/api/v1/message/${msg.ID}`)).json();link=(detail.HTML??'').replaceAll('&amp;','&').match(/href="([^"]+type=recovery[^"]*)"/)?.[1]??'';}if(!link)await new Promise(r=>setTimeout(r,300));}expect(link.includes('/commune/auth/confirm')).toBe(true);await request.get(link);await page.goto(link);await expect(page).toHaveURL(/step=confirm/);await page.locator('.commune-form button').click();await expect(page).toHaveURL('/en/commune/reset-password');await fillPassword(page.locator('[name="password"]'),recoveredPassword);await fillPassword(page.locator('[name="confirmation"]'),recoveredPassword);await page.locator('.commune-form button').click();await expect(page).toHaveURL('/en/commune/login?state=password-reset');await login(page,accounts.AGENT,recoveredPassword);await expect(page).toHaveURL('/en/commune');});
 test('disabled staff lose protected access on the next request',async({page})=>{await login(page,accounts.AGENT,recoveredPassword);await expect(page).toHaveURL('/en/commune');const db=postgres(localDatabaseUrl(),{max:1});try{await db`update app.application_profiles set access_status='DISABLED' where auth_user_id=(select id from auth.users where email=${accounts.AGENT})`;await page.goto('/en/commune/account');await expect(page).toHaveURL('/en/commune/account-disabled');await expect(page.getByRole('heading')).toContainText('disabled');}finally{await db.end();}});
});

for(const locale of ['ar','fr','en'])test(`Commune entry and safety states reflow in ${locale}`,async({page})=>{test.setTimeout(120000);for(const width of [1440,820,390,320]){await page.setViewportSize({width,height:1000});for(const route of ['login','forgot-password','reset-password','account-disabled','session-expired','access-denied']){await page.goto(`/${locale}/commune/${route}`);await expect(page.locator('h1')).toHaveCount(1);await expect(page.locator('h1')).toBeVisible();await expect(page.locator('html')).toHaveAttribute('dir',locale==='ar'?'rtl':'ltr');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/commune/${locale}-${route}-${width}.png`,fullPage:true,mask:[page.locator('input[name*=assword],input[name=confirmation]')]});}}await page.goto(`/${locale}/commune/login`);expect((await new AxeBuilder({page}).analyze()).violations.map(({id})=>id)).toEqual([]);});
