import {randomUUID} from 'node:crypto';
import {test,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import postgres from 'postgres';
import {expect,fillPassword} from '../support/private-password-input';
import {disposablePassword} from '../support/disposable-password';
import {localFixtureAuth} from '../support/local-fixtures';
import {bootstrapLocalStaff} from '../../scripts/local-staff';
import {runtimeDatabaseUrl} from '../database/target';
import {canonicalCategories,canonicalLocations} from '../../fixtures/canonical-catalogue';
test.use({trace:'off',screenshot:'off',video:'off'});
const citizenEmail=`dev05-citizen-${randomUUID()}@example.test`,citizenPassword=disposablePassword(),staffEmail=`dev05-agent-${randomUUID()}@example.test`,staffPassword=disposablePassword();
async function citizenLogin(page:Page){await page.goto('/en/login');await page.getByLabel('Email address').fill(citizenEmail);await fillPassword(page.locator('input[name="password"]'),citizenPassword);await page.locator('form').filter({has:page.locator('input[name="password"]')}).locator('button[type="submit"]').click();await expect(page).toHaveURL('/en/citizen');}
async function staffLogin(page:Page){await page.goto('/en/commune/login');await page.locator('input[name="email"]').fill(staffEmail);await fillPassword(page.locator('input[name="password"]'),staffPassword);await page.locator('.commune-form button').click();await expect(page).toHaveURL('/en/commune');}
async function submit(page:Page,subject:string){await page.goto('/en/citizen/complaints/new');const category=page.locator('#categoryId');await expect.poll(()=>category.evaluate(element=>Object.keys(element).some(key=>key.startsWith('__reactProps$')))).toBe(true);await category.selectOption(canonicalCategories[0].id);await page.locator('#subject').fill(subject);await page.locator('#description').fill('A sufficiently detailed DEV-05 complaint used for tracking and intake review.');await page.getByRole('button',{name:'Next',exact:true}).click();await page.locator('#locationId').selectOption(canonicalLocations[0].id);await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Confirm and submit',exact:true}).click();await expect(page).toHaveURL(/\/en\/citizen\/complaints\/AB-/);return page.url().match(/AB-[A-Z2-9-]+/)![0];}
test.describe.serial('DEV-05 Citizen tracking and shared Commune intake',()=>{
 test.setTimeout(120_000);
 test.beforeAll(async()=>{await bootstrapLocalStaff({email:staffEmail,password:staffPassword,fullName:'DEV05 Review Agent',role:'AGENT',language:'en'});const auth=localFixtureAuth(),created=await auth.auth.admin.createUser({email:citizenEmail,password:citizenPassword,email_confirm:true});expect(created.error).toBeNull();const db=postgres(runtimeDatabaseUrl(),{max:1,onnotice:()=>{}});try{const [legal]=await db`select * from app.read_signup_legal('en')`;await db`select * from app.provision_citizen(${created.data.user!.id},'DEV05 Review Citizen',${'+212600000001'},'en',${legal.terms_version_id},${legal.privacy_version_id})`;}finally{await db.end();}});
 test('Citizen lists, searches, edits and withdraws only while submitted',async({page})=>{await citizenLogin(page);const editable=await submit(page,'Road issue for editing');await page.goto('/en/citizen/complaints');await expect(page.getByText(editable)).toBeVisible();await page.getByLabel('Search by reference or subject').fill('Road issue');await page.getByRole('button',{name:'Apply'}).click();await expect(page.getByText(editable)).toBeVisible();await page.getByRole('link',{name:'View details'}).click();await page.getByRole('link',{name:'Edit complaint'}).click();await page.getByLabel('Short subject').fill('Edited road issue');await page.getByRole('button',{name:'Save changes'}).click();await expect(page).toHaveURL(`/en/citizen/complaints/${editable}?state=edited`);await expect(page.getByText('Complaint information edited')).toBeVisible();const withdrawn=await submit(page,'Complaint to withdraw');await page.getByRole('button',{name:'Withdraw complaint'}).click();const confirmation=page.getByRole('dialog',{name:'Withdraw complaint'});await expect(confirmation).toBeVisible();await confirmation.getByRole('button',{name:'Withdraw complaint'}).click();await expect(page).toHaveURL(`/en/citizen/complaints/${withdrawn}?state=withdrawn`);await expect(page.locator('.detail-status').getByText('Withdrawn')).toBeVisible();await expect(page.getByRole('link',{name:'Edit complaint'})).toHaveCount(0);});
 test('Agent uses shared inbox, starts review, and both audiences receive notifications',async({browser})=>{const citizenContext=await browser.newContext(),staffContext=await browser.newContext(),citizen=await citizenContext.newPage(),staff=await staffContext.newPage();try{await citizenLogin(citizen);const reference=await submit(citizen,'Shared intake review');await staffLogin(staff);await staff.goto('/en/commune/complaints');await staff.getByLabel('Search by reference, subject, or Citizen').fill(reference);await staff.getByRole('button',{name:'Apply'}).click();await expect(staff.getByText(reference)).toBeVisible();await staff.getByRole('link',{name:'View details'}).click();await expect(staff.getByText('DEV05 Review Citizen')).toBeVisible();await expect(staff.getByText(citizenEmail)).toBeVisible();await staff.getByRole('button',{name:'Start review'}).click();const confirmation=staff.getByRole('dialog',{name:'Start review'});await expect(confirmation).toBeVisible();await confirmation.getByRole('button',{name:'Start review'}).click();await expect(staff).toHaveURL(`/en/commune/complaints/${reference}?state=reviewing`);await expect(staff.locator('.complaint-panel').getByText('Under review')).toBeVisible();await staff.goto('/en/commune/notifications');await expect(staff.getByText('New complaint').first()).toBeVisible();await expect(staff.getByText('Complaint withdrawn')).toBeVisible();const badge=staff.locator('.notification-badge'),before=Number(await badge.textContent());await staff.getByRole('button',{name:/Open complaint/}).first().click();await expect.poll(async()=>Number(await badge.textContent().catch(()=>0))).toBe(before-1);await staff.goto('/en/commune/notifications');await staff.getByRole('button',{name:'Mark all as read'}).click();await expect(badge).toHaveCount(0);await citizen.goto(`/en/citizen/complaints/${reference}`);await expect(citizen.locator('.complaint-panel').getByText('Under review')).toBeVisible();await expect(citizen.getByRole('link',{name:'Edit complaint'})).toHaveCount(0);await citizen.goto('/en/citizen/notifications');await expect(citizen.getByText('Your complaint is under review')).toBeVisible();}finally{await citizenContext.close();await staffContext.close();}});
 test('AR/FR/EN direction, keyboard-accessible filters and representative 320px reflow',async({page})=>{await citizenLogin(page);for(const locale of ['ar','fr','en'] as const){await page.goto(`/${locale}/citizen/complaints`);await expect(page.locator('html')).toHaveAttribute('dir',locale==='ar'?'rtl':'ltr');await page.setViewportSize({width:320,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await page.goto('/en/citizen/complaints');expect((await new AxeBuilder({page}).include('.tracking-page').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(({id})=>id)).toEqual([]);});
});
