import {test,type Page} from '@playwright/test';
import {expect,fillPassword} from '../support/private-password-input';
import {randomUUID} from 'node:crypto';
import {join} from 'node:path';
import postgres from 'postgres';
import AxeBuilder from '@axe-core/playwright';
import {bootstrapLocalStaff} from '../../scripts/local-staff';
import {localDatabaseUrl} from '../../scripts/local-target';
import {disposablePassword} from '../support/disposable-password';
import {localFixtureAuth} from '../support/local-fixtures';
import {runtimeDatabaseUrl} from '../database/target';
import type {AdminPublicationBundle,AdminSettingsBundle} from '../../src/features/content-admin/model';

test.use({trace:'off',screenshot:'off',video:'off'});
test.describe.serial('DEV-09 public content and settings administration',()=>{test.setTimeout(240_000);
 const adminEmail=`dev09-admin-${randomUUID()}@example.test`,agentEmail=`dev09-agent-${randomUUID()}@example.test`,citizenEmail=`dev09-citizen-${randomUUID()}@example.test`,adminPassword=disposablePassword(),agentPassword=disposablePassword(),citizenPassword=disposablePassword(),marker=randomUUID().slice(0,8);let originalPage:AdminPublicationBundle,originalPrivacy:AdminPublicationBundle,originalSettings:{phone:string;email:string;url:string;bundle:AdminSettingsBundle},citizenId='',acknowledgementSignature='';
 async function staffLogin(page:Page,email:string,password:string,locale='en'){await page.goto(`/${locale}/commune/login`);await page.locator('[name=email]').fill(email);await fillPassword(page.locator('[name=password]'),password);await page.locator('.commune-form button').click();await expect(page).toHaveURL(`/${locale}/commune`,{timeout:30_000});}
 async function citizenLogin(page:Page){await page.goto('/en/login');await page.locator('[name=email]').fill(citizenEmail);await fillPassword(page.locator('[name=password]'),citizenPassword);await page.locator('form').filter({has:page.locator('[name=password]')}).locator('button[type=submit]').click();await expect(page).toHaveURL('/en/citizen',{timeout:30_000});}
 async function publish(page:Page,bundle:AdminPublicationBundle){const before=Number(await page.locator('[name=revision]').getAttribute('value'));for(const language of ['ar','fr','en'] as const){await page.locator(`[name=${language}Title]`).fill(bundle[language].title);await page.locator(`[name=${language}Body]`).fill(bundle[language].body);}await page.getByRole('button',{name:'Publish new version'}).click();await page.getByRole('dialog',{name:'Publish this multilingual version?'}).getByRole('button',{name:'Publish new version'}).click();await expect.poll(async()=>Number(await page.locator('[name=revision]').getAttribute('value')),{timeout:30_000}).toBeGreaterThan(before);}
 async function saveSettings(page:Page,settings:typeof originalSettings){const before=Number(await page.locator('[name=revision]').getAttribute('value'));await page.locator('[name=contactPhone]').fill(settings.phone);await page.locator('[name=contactEmail]').fill(settings.email);await page.locator('[name=chikayaUrl]').selectOption(settings.url);for(const language of ['ar','fr','en'] as const){await page.locator(`[name=${language}CommuneName]`).fill(settings.bundle[language].commune_name);await page.locator(`[name=${language}PublicAddress]`).fill(settings.bundle[language].public_address);await page.locator(`[name=${language}OpeningHours]`).fill(settings.bundle[language].opening_hours);}await page.getByRole('button',{name:'Save public settings'}).click();await page.getByRole('dialog',{name:'Save these public settings?'}).getByRole('button',{name:'Save public settings'}).click();await expect.poll(async()=>Number(await page.locator('[name=revision]').getAttribute('value')),{timeout:30_000}).toBeGreaterThan(before);}
 test.beforeAll(async()=>{test.setTimeout(120_000);process.env.PATH=join(process.env.LOCALAPPDATA??'','Programs','Podman')+';'+process.env.PATH;process.env.DOCKER_HOST='npipe:////./pipe/podman-machine-default';await bootstrapLocalStaff({email:adminEmail,password:adminPassword,fullName:'DEV09 Administrator',role:'ADMIN',language:'en'});await bootstrapLocalStaff({email:agentEmail,password:agentPassword,fullName:'DEV09 Agent',role:'AGENT',language:'en'});const auth=localFixtureAuth(),created=await auth.auth.admin.createUser({email:citizenEmail,password:citizenPassword,email_confirm:true,user_metadata:{language:'en'}});if(created.error||!created.data.user)throw new Error('Citizen fixture creation failed');const runtime=postgres(runtimeDatabaseUrl(),{max:1,onnotice:()=>{}});try{const [legal]=await runtime`select * from app.read_signup_legal('en')`;const [profile]=await runtime`select * from app.provision_citizen(${created.data.user.id},'DEV09 Citizen',null,'en',${legal.terms_version_id},${legal.privacy_version_id})`;citizenId=profile.profile_id;}finally{await runtime.end();}const db=postgres(localDatabaseUrl(),{max:1,onnotice:()=>{}});try{const pages=await db`select p.page_key,jsonb_object_agg(t.language,jsonb_build_object('title',t.title,'body',t.body)) translations from app.public_pages p join app.public_page_versions v on v.page_id=p.id and v.version_number=p.current_version join app.public_page_translations t on t.version_id=v.id where p.page_key in ('HOME','PRIVACY') group by p.page_key`;originalPage=pages.find(row=>row.page_key==='HOME')!.translations as AdminPublicationBundle;originalPrivacy=pages.find(row=>row.page_key==='PRIVACY')!.translations as AdminPublicationBundle;const [settings]=await db`select s.contact_phone,s.contact_email,s.chikaya_url,jsonb_object_agg(t.language,jsonb_build_object('commune_name',t.commune_name,'public_address',t.public_address,'opening_hours',t.opening_hours)) translations from app.commune_settings s join app.commune_settings_translations t on t.settings_id=s.id group by s.id`;originalSettings={phone:settings.contact_phone,email:settings.contact_email,url:settings.chikaya_url,bundle:settings.translations as AdminSettingsBundle};const acknowledgements=await db`select page_version_id,language,acknowledged_at from app.legal_acknowledgements where citizen_id=${citizenId} order by page_version_id`;acknowledgementSignature=JSON.stringify(acknowledgements);}finally{await db.end();}});
 test('Admin previews and publishes fixed content, updates settings, and restores review values',async({page})=>{await staffLogin(page,adminEmail,adminPassword);await page.goto('/en/commune/settings');await expect(page.getByRole('heading',{name:'Settings'})).toBeVisible();await expect(page.getByRole('link',{name:/Public content/})).toBeVisible();await page.locator('.settings-cards a[href="/en/commune/settings/pages"]').click();await expect(page.locator('.content-page-list article')).toHaveCount(6);await expect(page.locator('a[href$="/pages/PRIVACY"]')).toHaveCount(0);await page.goto('/en/commune/settings/pages?group=legal');await expect(page.locator('.content-page-list article')).toHaveCount(3);await expect(page.locator('a[href$="/pages/HOME"]')).toHaveCount(0);await page.goto('/en/commune/settings/pages/HOME');await expect(page.getByRole('heading',{name:'Home'})).toBeVisible();expect((await new AxeBuilder({page}).include('.content-detail').analyze()).violations.map(v=>v.id)).toEqual([]);
  const changed=structuredClone(originalPage);changed.en.title=`DEV09 public title ${marker}`;changed.fr.title=`Titre public DEV09 ${marker}`;changed.ar.title=`عنوان عام ${marker}`;await page.locator('[name=enTitle]').fill(changed.en.title);await expect(page.locator('.content-preview')).toContainText(changed.en.title);const publicTab=await page.context().newPage();await publicTab.goto('/en');await expect(publicTab.locator('.public-hero h1')).toHaveText(originalPage.en.title);await publicTab.close();await publish(page,changed);await page.goto(`/en?publication=${marker}`);await expect(page.locator('.public-hero h1')).toHaveText(changed.en.title);await page.goto('/en/commune/settings/pages/HOME');await expect(page.locator('.publication-history')).toContainText('Previous');await publish(page,originalPage);await page.goto(`/en?restored=${marker}`);await expect(page.locator('.public-hero h1')).toHaveText(originalPage.en.title);
  await page.goto('/en/commune/settings/commune');const changedSettings=structuredClone(originalSettings);changedSettings.phone='+212 500 000 123';for(const language of ['ar','fr','en'] as const)changedSettings.bundle[language].commune_name=`${language} Commune ${marker}`;changedSettings.url=originalSettings.url==='https://chikaya.ma/'?'https://www.chikaya.ma/':'https://chikaya.ma/';changedSettings.bundle.en.opening_hours=`DEV09 hours ${marker}`;await saveSettings(page,changedSettings);for(const language of ['ar','fr','en'] as const){await page.goto(`/${language}/contact`);await expect(page.locator('.brand b')).toHaveText(changedSettings.bundle[language].commune_name);await expect(page.locator('.public-footer>small')).toContainText(changedSettings.bundle[language].commune_name);}await page.goto('/en/contact');await expect(page.locator('.contact')).toContainText(changedSettings.phone);await expect(page.locator('.chikaya a')).toHaveAttribute('href',changedSettings.url);await page.goto('/en/commune/settings/commune');await saveSettings(page,originalSettings);await page.goto('/en/contact');await expect(page.locator('.contact')).toContainText(originalSettings.phone);
  await page.goto('/ar/commune/settings/pages/HOME');await expect(page.locator('html')).toHaveAttribute('dir','rtl');await page.setViewportSize({width:320,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
 test('Privacy publication preserves existing Citizen acknowledgement and access',async({page,browser})=>{await staffLogin(page,adminEmail,adminPassword);await page.goto('/en/commune/settings/pages/PRIVACY');const changed=structuredClone(originalPrivacy);changed.en.title=`DEV09 Privacy ${marker}`;await publish(page,changed);const citizenContext=await browser.newContext({baseURL:'http://127.0.0.1:3000'});try{const citizenPage=await citizenContext.newPage();await citizenLogin(citizenPage);await expect(citizenPage.getByRole('heading',{name:/Welcome/})).toBeVisible();const db=postgres(localDatabaseUrl(),{max:1,onnotice:()=>{}});try{const rows=await db`select page_version_id,language,acknowledged_at from app.legal_acknowledgements where citizen_id=${citizenId} order by page_version_id`;expect(JSON.stringify(rows)).toBe(acknowledgementSignature);}finally{await db.end();}}finally{await citizenContext.close();}await page.goto('/en/commune/settings/pages/PRIVACY');await publish(page,originalPrivacy);});
 test('Agent is denied content and settings administration',async({page})=>{await staffLogin(page,agentEmail,agentPassword);await page.goto('/fr/commune/settings');await expect(page).toHaveURL('/fr/commune/access-denied');});
});
