import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import postgres from 'postgres';
import {canonicalCategories,canonicalLocations} from '../../fixtures/canonical-catalogue';
import {localDatabaseUrl,runtimeDatabaseUrl} from './target';

export async function verifyDev06(adminUrl=localDatabaseUrl()){
 const env=readFileSync('.env.local','utf8'),runtime=new URL(env.match(/^DATABASE_URL=(.+)$/m)?.[1]??runtimeDatabaseUrl());runtime.pathname=new URL(adminUrl).pathname;
 const admin=postgres(adminUrl,{max:4,onnotice:()=>{}}),web=postgres(runtime.href,{max:8,onnotice:()=>{}});let passed=0;
 const check=(value:unknown,label:string)=>{assert.ok(value,label);passed++;console.log(`PASS ${label}`);};
 const rejects=async(fn:()=>Promise<unknown>,code:string,label:string)=>{await assert.rejects(fn,error=>(error as {code?:string}).code===code,label);check(true,label);};
 try{
  const [legal]=await web`select * from app.read_signup_legal('en')`;
  const auth=randomUUID(),provider=randomUUID(),digest=randomBytes(32);await admin`insert into auth.users(id,email,email_confirmed_at) values(${auth},${`${auth}@example.invalid`},now())`;const [citizen]=await web`select * from app.provision_citizen(${auth},'DEV06 Citizen','+212600000000','fr',${legal.terms_version_id},${legal.privacy_version_id})`;await web`select * from app.create_citizen_session(${auth},${provider},${digest})`;
  const staffAuth=randomUUID(),staffProvider=randomUUID(),staffDigest=randomBytes(32);await admin`insert into auth.users(id,email,email_confirmed_at) values(${staffAuth},${`${staffAuth}@example.invalid`},now())`;await admin`insert into app.application_profiles(auth_user_id,full_name,role,access_status) values(${staffAuth},'DEV06 Agent','AGENT','ACTIVE')`;await web`select * from app.create_application_session(${staffAuth},${staffProvider},${staffDigest},'COMMUNE')`;
  const submit=async()=>{const [row]=await web`select * from app.submit_complaint(${auth},${provider},${digest},${randomUUID()},${randomBytes(32)},${canonicalCategories[0].id},${canonicalLocations[0].id},'Lifecycle verification','A sufficiently detailed complaint for DEV-06 lifecycle verification.',null,true)`;return row;};
  const review=async(reference:string)=>{const [c]=await web`select * from app.read_staff_complaint(${staffAuth},${staffProvider},${staffDigest},${reference})`;await web`select * from app.start_complaint_review(${staffAuth},${staffProvider},${staffDigest},${reference},${c.revision},${randomUUID()},${randomBytes(32)})`;};
  const normal=await submit();await review(normal.reference);let [detail]=await web`select * from app.read_staff_complaint(${staffAuth},${staffProvider},${staffDigest},${normal.reference})`;
  const processKey=randomUUID(),processPrint=randomBytes(32);const process=()=>web`select * from app.start_complaint_processing(${staffAuth},${staffProvider},${staffDigest},${normal.reference},${detail.revision},${processKey},${processPrint})`;const [processed]=await process(),[processReplay]=await process();check(Number(processed.revision)===3&&processReplay.replayed,'UNDER_REVIEW to IN_PROCESSING is atomic and idempotent');
  check((await admin`select count(*)::int n from app.notifications where complaint_id=(select id from app.complaints where reference=${normal.reference}) and recipient_id=${citizen.profile_id} and type='IN_PROCESSING'`)[0].n===1,'processing creates one Citizen notification and no email');
  detail=(await web`select * from app.read_staff_complaint(${staffAuth},${staffProvider},${staffDigest},${normal.reference})`)[0];const responseKey=randomUUID(),responsePrint=randomBytes(32);const respond=()=>web`select * from app.issue_complaint_response(${staffAuth},${staffProvider},${staffDigest},${normal.reference},${detail.revision},${responseKey},${responsePrint},'  Réponse conservée exactement 😀  ')`;const [responded]=await respond(),[responseReplay]=await respond();check(Number(responded.revision)===4&&responseReplay.replayed,'IN_PROCESSING to RESPONSE_SENT is atomic and idempotent');
  let versions=await web`select * from app.read_own_response_versions(${auth},${provider},${digest},${normal.reference})`;check(versions.length===1&&versions[0].body==='  Réponse conservée exactement 😀  '&&versions[0].response_kind==='NORMAL','Citizen reads exact preserved response version 1');
  check((await admin`select count(*)::int n from app.email_outbox where complaint_id=(select id from app.complaints where reference=${normal.reference}) and event_type='RESPONSE'`)[0].n===1,'response creates one RESPONSE outbox intent');
  await rejects(()=>web`update app.response_versions set body='changed'`,'42501','runtime cannot mutate response versions directly');
  await rejects(()=>web`select * from app.correct_complaint_response(${staffAuth},${staffProvider},${staffDigest},${normal.reference},4,${randomUUID()},${randomBytes(32)},'Corrected response','Reason',false)`,'42501','correction rejects missing password-reauth proof');
  const correctionKey=randomUUID(),correctionPrint=randomBytes(32);const correct=()=>web`select * from app.correct_complaint_response(${staffAuth},${staffProvider},${staffDigest},${normal.reference},4,${correctionKey},${correctionPrint},'Corrected response','Required correction reason',true)`;const [corrected]=await correct(),[correctionReplay]=await correct();check(Number(corrected.revision)===5&&correctionReplay.replayed,'RESPONSE_SENT correction is revisioned and idempotent');versions=await web`select * from app.read_own_response_versions(${auth},${provider},${digest},${normal.reference})`;check(versions.length===2&&Number(versions[0].version_number)===2&&Number(versions[1].version_number)===1,'correction preserves contiguous immutable history and selects latest first');
  await rejects(()=>web`select * from app.correct_complaint_response(${staffAuth},${staffProvider},${staffDigest},${normal.reference},5,${randomUUID()},${randomBytes(32)},'Body',' ',true)`,'23514','blank correction reason is denied');
  detail=(await web`select * from app.read_staff_complaint(${staffAuth},${staffProvider},${staffDigest},${normal.reference})`)[0];const closeKey=randomUUID(),closePrint=randomBytes(32);const close=()=>web`select * from app.close_complaint(${staffAuth},${staffProvider},${staffDigest},${normal.reference},${detail.revision},${closeKey},${closePrint})`;const [closed]=await close(),[closeReplay]=await close();check(Number(closed.revision)===6&&closeReplay.replayed,'RESPONSE_SENT to CLOSED is atomic and idempotent');
  detail=(await web`select * from app.read_staff_complaint(${staffAuth},${staffProvider},${staffDigest},${normal.reference})`)[0];check(detail.status==='CLOSED','normal response closes only after response issuance');
  const closedCorrection=await web`select * from app.correct_complaint_response(${staffAuth},${staffProvider},${staffDigest},${normal.reference},${detail.revision},${randomUUID()},${randomBytes(32)},'Post-closure corrected response','Post-closure correction reason',true)`;check(Number(closedCorrection[0].revision)===7&&(await web`select * from app.read_staff_complaint(${staffAuth},${staffProvider},${staffDigest},${normal.reference})`)[0].status==='CLOSED','correction after CLOSED preserves terminal state');
  await rejects(()=>web`select * from app.start_complaint_processing(${staffAuth},${staffProvider},${staffDigest},${normal.reference},7,${randomUUID()},${randomBytes(32)})`,'P0412','CLOSED cannot reopen');
  check((await admin`select count(*)::int n from app.email_outbox where complaint_id=(select id from app.complaints where reference=${normal.reference}) and event_type='CLOSURE'`)[0].n===1,'closure creates one CLOSURE intent');
  for(const [reason,fromProcessing] of [['OUT_OF_SCOPE',false],['INSUFFICIENT_INFORMATION',true]] as const){const item=await submit();await review(item.reference);if(fromProcessing){const [d]=await web`select * from app.read_staff_complaint(${staffAuth},${staffProvider},${staffDigest},${item.reference})`;await web`select * from app.start_complaint_processing(${staffAuth},${staffProvider},${staffDigest},${item.reference},${d.revision},${randomUUID()},${randomBytes(32)})`;}
   const [d]=await web`select * from app.read_staff_complaint(${staffAuth},${staffProvider},${staffDigest},${item.reference})`;await web`select * from app.not_accept_complaint(${staffAuth},${staffProvider},${staffDigest},${item.reference},${d.revision},${randomUUID()},${randomBytes(32)},${reason},${`Explanation for ${reason}`})`;const [rejected]=await web`select * from app.read_staff_complaint(${staffAuth},${staffProvider},${staffDigest},${item.reference})`;check(rejected.status==='NOT_ACCEPTED',`${reason} rejection works from ${fromProcessing?'IN_PROCESSING':'UNDER_REVIEW'}`);check((await web`select app.read_own_rejection_reason(${auth},${provider},${digest},${item.reference}) reason`)[0].reason===reason,`${reason} is projected only to owning Citizen`);await rejects(()=>web`select * from app.close_complaint(${staffAuth},${staffProvider},${staffDigest},${item.reference},${rejected.revision},${randomUUID()},${randomBytes(32)})`,'P0412','NOT_ACCEPTED has no closure path');check((await admin`select count(*)::int n from app.email_outbox where complaint_id=(select id from app.complaints where reference=${item.reference}) and event_type='CLOSURE'`)[0].n===0,'NOT_ACCEPTED creates no closure email');
   const [afterCorrection]=await web`select * from app.correct_complaint_response(${staffAuth},${staffProvider},${staffDigest},${item.reference},${rejected.revision},${randomUUID()},${randomBytes(32)},'Corrected rejection explanation','Correction reason',true)`;check(Number(afterCorrection.revision)===Number(rejected.revision)+1&&(await web`select app.read_own_rejection_reason(${auth},${provider},${digest},${item.reference}) reason`)[0].reason===reason,'NOT_ACCEPTED correction preserves controlled reason and terminal state');}
  const race=await submit();await review(race.reference);const [raceDetail]=await web`select * from app.read_staff_complaint(${staffAuth},${staffProvider},${staffDigest},${race.reference})`;const attempts=await Promise.allSettled([web`select * from app.start_complaint_processing(${staffAuth},${staffProvider},${staffDigest},${race.reference},${raceDetail.revision},${randomUUID()},${randomBytes(32)})`,web`select * from app.not_accept_complaint(${staffAuth},${staffProvider},${staffDigest},${race.reference},${raceDetail.revision},${randomUUID()},${randomBytes(32)},'OUT_OF_SCOPE','Race rejection explanation')`]);check(attempts.filter(x=>x.status==='fulfilled').length===1&&attempts.filter(x=>x.status==='rejected'&&(x.reason as {code?:string}).code==='P0412').length===1,'incompatible lifecycle race has exactly one winner');
  await rejects(()=>web`select * from app.response_versions`,'42501','runtime has no raw response-table access');
  const outsiderAuth=randomUUID(),outsiderProvider=randomUUID(),outsiderDigest=randomBytes(32);await admin`insert into auth.users(id,email,email_confirmed_at) values(${outsiderAuth},${`${outsiderAuth}@example.invalid`},now())`;await web`select * from app.provision_citizen(${outsiderAuth},'Other Citizen',null,'en',${legal.terms_version_id},${legal.privacy_version_id})`;await web`select * from app.create_citizen_session(${outsiderAuth},${outsiderProvider},${outsiderDigest})`;check((await web`select * from app.read_own_response_versions(${outsiderAuth},${outsiderProvider},${outsiderDigest},${normal.reference})`).length===0,'Citizen response isolation is enforced');
  check((await admin`select count(*)::int n from app.complaint_events e join app.audit_events a on a.id=e.audit_event_id where e.complaint_id=(select id from app.complaints where reference=${normal.reference}) and a.resource_id=e.complaint_id`)[0].n>=7,'lifecycle events retain matching audit evidence');
  console.log(`DEV-06 database: ${passed} checks passed.`);
 }finally{await web.end();await admin.end();}
}
