import assert from 'node:assert/strict';import {randomBytes,randomUUID} from 'node:crypto';import {readFileSync} from 'node:fs';import postgres from 'postgres';import {canonicalCategories} from '../../fixtures/canonical-catalogue';import {seedCatalogues} from '../../scripts/seed-catalogues';import {localDatabaseUrl,runtimeDatabaseUrl} from './target';
export async function verifyDev08(adminUrl=localDatabaseUrl()){const env=readFileSync('.env.local','utf8'),runtime=new URL(env.match(/^DATABASE_URL=(.+)$/m)?.[1]??runtimeDatabaseUrl());runtime.pathname=new URL(adminUrl).pathname;const admin=postgres(adminUrl,{max:4,onnotice:()=>{}}),web=postgres(runtime.href,{max:6,onnotice:()=>{}});let passed=0;const check=(value:unknown,label:string)=>{assert.ok(value,label);passed++;console.log(`PASS ${label}`);};const rejects=async(fn:()=>Promise<unknown>,code:string,label:string)=>{await assert.rejects(fn,error=>{if((error as {code?:string}).code!==code)console.log('DEV08 rejection diagnostic',label,(error as {code?:string;message?:string}).code,(error as {message?:string}).message);return (error as {code?:string}).code===code;},label);check(true,label);};try{
 const make=async(role:'ADMIN'|'AGENT'|'CITIZEN')=>{const auth=randomUUID(),provider=randomUUID(),digest=randomBytes(32);await admin`insert into auth.users(id,email,email_confirmed_at) values(${auth},${`${auth}@example.invalid`},now())`;let profile;if(role==='CITIZEN'){const [legal]=await web`select * from app.read_signup_legal('en')`;[profile]=await web`select * from app.provision_citizen(${auth},'DEV08 Citizen',null,'en',${legal.terms_version_id},${legal.privacy_version_id})`;}else [profile]=await admin`insert into app.application_profiles(auth_user_id,full_name,role,access_status) values(${auth},${`DEV08 ${role}`},${role},'ACTIVE') returning *`;await web`select * from app.create_application_session(${auth},${provider},${digest},${role==='CITIZEN'?'CITIZEN':'COMMUNE'})`;return {auth,provider,digest,profile};};
 const owner=await make('ADMIN'),agent=await make('AGENT'),citizen=await make('CITIZEN');
 check((await web`select * from app.list_admin_catalogues(${owner.auth},${owner.provider},${owner.digest},'CATEGORY',null,'ALL')`).length===7,'Admin lists all canonical categories');
 await rejects(()=>web`select * from app.list_admin_catalogues(${agent.auth},${agent.provider},${agent.digest},'CATEGORY',null,'ALL')`,'42501','Agent cannot list catalogue administration');
 const categoryKey=randomUUID(),categoryFingerprint=randomBytes(32),createCategory=()=>web`select * from app.create_catalogue(${owner.auth},${owner.provider},${owner.digest},'CATEGORY',${categoryKey},${categoryFingerprint},'فئة تجريبية',null,null)`;
 const [category]=await createCategory(),[categoryReplay]=await createCategory();check(/^CAT_[A-F0-9]{12}$/.test(category.code)&&categoryReplay.replayed,'Category gets opaque code and command replay');check(!(await admin`select is_active from app.categories where id=${category.id}`)[0].is_active,'New category starts inactive');
 await rejects(()=>web`select * from app.create_catalogue(${citizen.auth},${citizen.provider},${citizen.digest},'CATEGORY',${randomUUID()},${randomBytes(32)},'ممنوع',null,null)`,'42501','Citizen mutation denied');
 await rejects(()=>web`select * from app.set_catalogue_active(${owner.auth},${owner.provider},${owner.digest},'CATEGORY',${category.id},1,${randomUUID()},${randomBytes(32)},true)`,'P0801','Category activation requires ar fr en');
 const updateKey=randomUUID(),updateFingerprint=randomBytes(32),update=()=>web`select * from app.update_catalogue(${owner.auth},${owner.provider},${owner.digest},'CATEGORY',${category.id},1,${updateKey},${updateFingerprint},'فئة تجريبية','Catégorie test','Test category')`;const [categoryUpdated]=await update(),[updateReplay]=await update();check(Number(categoryUpdated.revision)===2&&updateReplay.replayed,'Category translation update is revisioned and idempotent');await rejects(()=>web`select * from app.update_catalogue(${owner.auth},${owner.provider},${owner.digest},'CATEGORY',${category.id},1,${randomUUID()},${randomBytes(32)},'قديم','Ancien','Old')`,'P0812','Stale catalogue edit rejected');
 const [categoryActive]=await web`select * from app.set_catalogue_active(${owner.auth},${owner.provider},${owner.digest},'CATEGORY',${category.id},2,${randomUUID()},${randomBytes(32)},true)`;check(Number(categoryActive.revision)===3,'Complete category activates');
 const locationKey=randomUUID(),locationFingerprint=randomBytes(32),[location]=await web`select * from app.create_catalogue(${owner.auth},${owner.provider},${owner.digest},'LOCATION',${locationKey},${locationFingerprint},'دوار الاختبار',null,null)`;check(/^LOC_[A-F0-9]{12}$/.test(location.code),'Location gets opaque nonsequential code');const [locationActive]=await web`select * from app.set_catalogue_active(${owner.auth},${owner.provider},${owner.digest},'LOCATION',${location.id},1,${randomUUID()},${randomBytes(32)},true)`;check(Number(locationActive.revision)===2,'Arabic-only location activates without invented translations');check((await admin`select count(*)::int n from app.location_translations where location_id=${location.id}`)[0].n===1,'No automatic location transliteration');
 await web`select * from app.update_catalogue(${owner.auth},${owner.provider},${owner.digest},'LOCATION',${location.id},2,${randomUUID()},${randomBytes(32)},'دوار الاختبار','Lieu approuvé','Approved place')`;check((await admin`select count(*)::int n from app.location_translations where location_id=${location.id}`)[0].n===3,'Approved optional location translations can be added');
 await rejects(()=>web`select * from app.category_translations`,'42501','Runtime raw catalogue read denied');await rejects(()=>web`update app.categories set is_active=false`,'42501','Runtime raw catalogue mutation denied');await rejects(()=>admin`update app.categories set code='CHANGED',revision=revision+1 where id=${category.id}`,'23514','Category code is immutable');await rejects(()=>admin`insert into app.category_translations(category_id,language,label) values(${category.id},'ar','Duplicate')`,'23505','Translation locale is unique per parent');
 const [submitted]=await web`select * from app.submit_complaint(${citizen.auth},${citizen.provider},${citizen.digest},${randomUUID()},${randomBytes(32)},${category.id},${location.id},'Catalogue snapshot','A sufficiently detailed complaint for catalogue snapshot verification.',null,true)`;const [before]=await web`select * from app.read_own_complaint(${citizen.auth},${citizen.provider},${citizen.digest},${submitted.reference})`;
 await web`select * from app.update_catalogue(${owner.auth},${owner.provider},${owner.digest},'CATEGORY',${category.id},3,${randomUUID()},${randomBytes(32)},'فئة معدلة','Catégorie renommée','Renamed category')`;const [renamedLocation]=await web`select * from app.update_catalogue(${owner.auth},${owner.provider},${owner.digest},'LOCATION',${location.id},3,${randomUUID()},${randomBytes(32)},'دوار معدل','Lieu renommé','Renamed place')`;const [afterRename]=await web`select * from app.read_own_complaint(${citizen.auth},${citizen.provider},${citizen.digest},${submitted.reference})`;check(afterRename.category_labels.ar===before.category_labels.ar&&afterRename.location_labels.ar===before.location_labels.ar,'Catalogue rename never rewrites historical snapshots');
 await web`select * from app.set_catalogue_active(${owner.auth},${owner.provider},${owner.digest},'CATEGORY',${category.id},4,${randomUUID()},${randomBytes(32)},false)`;await web`select * from app.set_catalogue_active(${owner.auth},${owner.provider},${owner.digest},'LOCATION',${location.id},${renamedLocation.revision},${randomUUID()},${randomBytes(32)},false)`;
 const editRows=await web`select * from app.read_own_edit_catalogues(${citizen.auth},${citizen.provider},${citizen.digest},${submitted.reference})`;check(editRows.some(row=>row.id===category.id&&!row.is_active&&row.is_current)&&editRows.some(row=>row.id===location.id&&!row.is_active&&row.is_current),'Citizen edit projection retains only current inactive values');const [edited]=await web`select * from app.edit_own_complaint(${citizen.auth},${citizen.provider},${citizen.digest},${submitted.reference},${before.revision},${randomUUID()},${randomBytes(32)},${category.id},${location.id},'Edited text only','Updated complaint text while retaining inactive catalogue values.',null)`;check(Number(edited.revision)===2,'Unchanged inactive current values can be retained');const [afterEdit]=await web`select * from app.read_own_complaint(${citizen.auth},${citizen.provider},${citizen.digest},${submitted.reference})`;check(afterEdit.category_labels.ar===before.category_labels.ar&&afterEdit.location_labels.ar===before.location_labels.ar,'Unchanged inactive edit preserves original snapshots');
 const [otherInactive]=await web`select * from app.create_catalogue(${owner.auth},${owner.provider},${owner.digest},'LOCATION',${randomUUID()},${randomBytes(32)},'دوار غير نشط',null,null)`;await rejects(()=>web`select * from app.edit_own_complaint(${citizen.auth},${citizen.provider},${citizen.digest},${submitted.reference},2,${randomUUID()},${randomBytes(32)},${category.id},${otherInactive.id},'Invalid inactive change','Attempt to select a different inactive location is rejected.',null)`,'P0402','Different inactive location cannot be selected');
 const staffFilters=await web`select * from app.read_staff_location_filters(${agent.auth},${agent.provider},${agent.digest})`;check(staffFilters.some(row=>row.id===location.id&&!row.is_active&&row.labels.ar===before.location_labels.ar),'Agent filter receives complaint-linked inactive snapshot');check(!staffFilters.some(row=>row.id===otherInactive.id),'Agent filter excludes unrelated inactive metadata');
 check((await admin`select count(*)::int n from app.audit_events where resource_id in (${category.id},${location.id}) and action in ('CATEGORY_CREATED','CATEGORY_UPDATED','CATEGORY_ACTIVATED','CATEGORY_DEACTIVATED','LOCATION_CREATED','LOCATION_UPDATED','LOCATION_ACTIVATED','LOCATION_DEACTIVATED')`)[0].n>=8,'Catalogue commands create frozen audit evidence');
 await admin`update app.category_translations set label='Admin-custom label' where category_id=${canonicalCategories[0].id} and language='en'`;await admin`update app.categories set is_active=false,revision=revision+1 where id=${canonicalCategories[0].id}`;await seedCatalogues(admin);const [seeded]=await admin`select c.is_active,t.label from app.categories c join app.category_translations t on t.category_id=c.id and t.language='en' where c.id=${canonicalCategories[0].id}`;check(!seeded.is_active&&seeded.label==='Admin-custom label','Bootstrap initializer preserves legitimate Admin labels and state');
 check((await admin`select count(*)::int n from app.categories`)[0].n>=8&&(await admin`select count(*)::int n from app.locations`)[0].n>=8,'Clean initializer and Admin additions coexist without new entities');
 if(new URL(adminUrl).pathname!==new URL(localDatabaseUrl()).pathname){const [candidate]=await admin`select c.id from app.categories c where c.id=any(${canonicalCategories.map(item=>item.id)}::uuid[]) and not exists(select 1 from app.complaints x where x.category_id=c.id) order by c.id limit 1`,fixture=canonicalCategories.find(item=>item.id===candidate?.id);assert.ok(fixture,'An unreferenced canonical category is required for the isolated collision test');await admin`drop trigger no_delete on app.category_translations`;await admin`drop trigger no_delete on app.categories`;await admin`delete from app.category_translations where category_id=${fixture.id}`;await admin`delete from app.categories where id=${fixture.id}`;await admin`insert into app.categories(id,code,is_active) values(${randomUUID()},${fixture.code},true)`;await assert.rejects(()=>seedCatalogues(admin),/Canonical identity conflict/);check(true,'Bootstrap initializer fails closed on a true ID/code collision');}
 console.log(`DEV-08 database: ${passed} checks passed.`);
 }finally{await web.end();await admin.end();}}

