import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import postgres from 'postgres';
import {localDatabaseUrl,runtimeDatabaseUrl} from './target';

export async function verifyDev10(adminUrl=localDatabaseUrl()){
 const env=readFileSync('.env.local','utf8'),runtime=new URL(env.match(/^DATABASE_URL=(.+)$/m)?.[1]??runtimeDatabaseUrl());runtime.pathname=new URL(adminUrl).pathname;
 const mailerUrl=new URL(env.match(/^MAILER_DATABASE_URL=(.+)$/m)?.[1]??'');mailerUrl.pathname=runtime.pathname;
 const admin=postgres(adminUrl,{max:3,onnotice:()=>{}}),web=postgres(runtime.href,{max:4,onnotice:()=>{}}),mailer=postgres(mailerUrl.href,{max:1,onnotice:()=>{}});let passed=0;
 const check=(value:unknown,label:string)=>{assert.ok(value,label);passed++;console.log(`PASS ${label}`);};
 const rejects=async(fn:()=>Promise<unknown>,code:string,label:string)=>{await assert.rejects(fn,error=>(error as {code?:string}).code===code,label);check(true,label);};
 try{
  const [activeCategory]=await admin`select id from app.categories where is_active order by id limit 1`;
  const [activeLocation]=await admin`select id from app.locations where is_active order by id limit 1`;
  assert.ok(activeCategory&&activeLocation,'DEV-10 requires an active catalogue item');
  const categoryId=activeCategory.id,locationId=activeLocation.id;
  const make=async(role:'ADMIN'|'AGENT'|'CITIZEN')=>{
   const auth=randomUUID(),provider=randomUUID(),digest=randomBytes(32);
   await admin`insert into auth.users(id,email,email_confirmed_at) values(${auth},${`${auth}@example.invalid`},now())`;
   let profile;
   if(role==='CITIZEN'){
    const [legal]=await web`select * from app.read_signup_legal('en')`;
    [profile]=await web`select * from app.provision_citizen(${auth},'DEV10 Citizen',null,'en',${legal.terms_version_id},${legal.privacy_version_id})`;
   }else [profile]=await admin`insert into app.application_profiles(auth_user_id,full_name,role,access_status) values(${auth},${`DEV10 ${role}`},${role},'ACTIVE') returning *`;
   await web`select * from app.create_application_session(${auth},${provider},${digest},${role==='CITIZEN'?'CITIZEN':'COMMUNE'})`;
   return {auth,provider,digest,id:String(profile.profile_id??profile.id)};
  };
  const owner=await make('ADMIN'),agent=await make('AGENT'),citizen=await make('CITIZEN');
  const [before]=await admin`select * from app.application_profiles where id=${citizen.id}`;
  const [submitted]=await web`select * from app.submit_complaint(${citizen.auth},${citizen.provider},${citizen.digest},${randomUUID()},${randomBytes(32)},${categoryId},${locationId},'DEV10 preserved case','A sufficiently detailed Citizen complaint for status-change testing.',null,true)`;
  const [editable]=await web`select * from app.submit_complaint(${citizen.auth},${citizen.provider},${citizen.digest},${randomUUID()},${randomBytes(32)},${categoryId},${locationId},'DEV10 editable case','A second sufficiently detailed Citizen complaint for denial testing.',null,true)`;
  const [complaintBefore]=await admin`select * from app.complaints where reference=${submitted.reference}`;
  const [editableBefore]=await admin`select revision from app.complaints where reference=${editable.reference}`;
  check(complaintBefore.citizen_id===citizen.id,'Citizen owns a persisted complaint before disabling');
  const list=await web`select * from app.list_citizen_accounts(${owner.auth},${owner.provider},${owner.digest},'DEV10','ACTIVE',1)`;
  check(list.some(row=>row.profile_id===citizen.id)&&list.every(row=>!('auth_user_id'in row)),'Admin list contains only minimal Citizen projection');
  check((await web`select * from app.list_citizen_accounts(${owner.auth},${owner.provider},${owner.digest},${citizen.auth},null,1)`).length===1,'Admin searches verified email');
  const [detail]=await web`select * from app.read_citizen_admin_account(${owner.auth},${owner.provider},${owner.digest},${citizen.id})`;
  check(detail.profile_id===citizen.id&&detail.access_status==='ACTIVE','Admin reads minimal Citizen detail');
  await rejects(()=>web`select * from app.list_citizen_accounts(${agent.auth},${agent.provider},${agent.digest},null,null,1)`,'42501','Agent cannot list Citizens');
  await rejects(()=>web`select * from app.read_citizen_admin_account(${citizen.auth},${citizen.provider},${citizen.digest},${citizen.id})`,'42501','Citizen cannot access administration');
  await rejects(()=>web`select * from app.list_citizen_accounts(${randomUUID()},${randomUUID()},${randomBytes(32)},null,null,1)`,'42501','Public cannot access administration');
  await rejects(()=>web`update app.application_profiles set access_status='DISABLED' where id=${citizen.id}`,'42501','Runtime cannot mutate profile status directly');
  const key=randomUUID(),fingerprint=randomBytes(32),disable=()=>web`select * from app.set_citizen_access(${owner.auth},${owner.provider},${owner.digest},${citizen.id},${before.revision},'DISABLED','Security review',${key},${fingerprint})`;
  await rejects(()=>web`select * from app.set_citizen_access(${agent.auth},${agent.provider},${agent.digest},${citizen.id},${before.revision},'DISABLED','Security review',${randomUUID()},${randomBytes(32)})`,'42501','Agent cannot disable Citizen');
  await rejects(()=>web`select * from app.set_citizen_access(${owner.auth},${owner.provider},${owner.digest},${citizen.id},${before.revision},'DISABLED','  ',${randomUUID()},${randomBytes(32)})`,'22023','Disable requires nonblank reason');
  const [disabled]=await disable(),[replayed]=await disable();
  check(disabled.access_status==='DISABLED'&&replayed.replayed,'Disable is idempotent');
  const [after]=await admin`select * from app.application_profiles where id=${citizen.id}`;
  check(Number(after.security_epoch)===Number(before.security_epoch)+1&&Number(after.revision)===Number(before.revision)+1,'Disable increments epoch and revision');
  check((await admin`select count(*)::int n from app.application_sessions where profile_id=${citizen.id} and revoked_at is null`)[0].n===0,'All Citizen application sessions revoked');
  check((await web`select * from app.resolve_application_session(${citizen.auth},${citizen.provider},${citizen.digest},false)`)[0].state!=='VALID','Existing Citizen session denied');
  check((await web`select * from app.create_application_session(${citizen.auth},${randomUUID()},${randomBytes(32)},'CITIZEN')`).length===0,'New Citizen application login denied');
  check((await web`select app.citizen_recovery_allowed(${`${citizen.auth}@example.invalid`}) allowed`)[0].allowed===false,'Disabled Citizen recovery is suppressed');
  await rejects(()=>web`select * from app.submit_complaint(${citizen.auth},${citizen.provider},${citizen.digest},${randomUUID()},${randomBytes(32)},${categoryId},${locationId},'Denied case','This complaint must not commit after disabling.',null,true)`,'42501','Disabled Citizen cannot submit');
  await rejects(()=>web`select * from app.edit_own_complaint(${citizen.auth},${citizen.provider},${citizen.digest},${editable.reference},${editableBefore.revision},${randomUUID()},${randomBytes(32)},${categoryId},${locationId},'Denied edit','The disabled Citizen must not edit this complaint.',null)`,'42501','Disabled Citizen cannot edit');
  await rejects(()=>web`select * from app.withdraw_own_complaint(${citizen.auth},${citizen.provider},${citizen.digest},${editable.reference},${editableBefore.revision},${randomUUID()},${randomBytes(32)})`,'42501','Disabled Citizen cannot withdraw');
  await rejects(()=>web`select * from app.update_citizen_profile(${citizen.auth},${citizen.provider},${citizen.digest},${after.revision},'Denied profile edit',null,'en')`,'42501','Disabled Citizen cannot change profile');
  await rejects(()=>web`select app.secure_citizen_sessions(${citizen.auth},'PASSWORD_RESET',null,null,null)`,'42501','Disabled Citizen cannot complete stale recovery');
  await rejects(()=>web`select app.secure_citizen_sessions(${citizen.auth},'EMAIL_CHANGE',null,null,null)`,'42501','Disabled Citizen cannot complete pending email change');
  const [staffDetail]=await web`select * from app.read_staff_complaint(${agent.auth},${agent.provider},${agent.digest},${submitted.reference})`;
  await web`select * from app.start_complaint_review(${agent.auth},${agent.provider},${agent.digest},${submitted.reference},${staffDetail.revision},${randomUUID()},${randomBytes(32)})`;
  const [reviewed]=await web`select * from app.read_staff_complaint(${agent.auth},${agent.provider},${agent.digest},${submitted.reference})`;
  await web`select * from app.start_complaint_processing(${agent.auth},${agent.provider},${agent.digest},${submitted.reference},${reviewed.revision},${randomUUID()},${randomBytes(32)})`;
  const [processing]=await web`select * from app.read_staff_complaint(${agent.auth},${agent.provider},${agent.digest},${submitted.reference})`;
  await web`select * from app.issue_complaint_response(${agent.auth},${agent.provider},${agent.digest},${submitted.reference},${processing.revision},${randomUUID()},${randomBytes(32)},'The Commune response remains available in the preserved case.')`;
  check((await admin`select status from app.complaints where id=${complaintBefore.id}`)[0].status==='RESPONSE_SENT','Commune processing continues for disabled Citizen');
  check((await admin`select count(*)::int n from app.notifications where complaint_id=${complaintBefore.id} and recipient_id=${citizen.id}`)[0].n===1,'Disabled Citizen receives no new in-app fanout');
  check((await admin`select count(*)::int n from app.email_outbox where complaint_id=${complaintBefore.id}`)[0].n===1,'Disabled Citizen receives no new email intent');
  const claimed=await mailer`select * from app.claim_email_outbox(20,120)`;
  check(!claimed.some(row=>row.reference===submitted.reference||row.reference===editable.reference),'Previously queued Citizen receipts are not delivered after disabling');
  check((await admin`select count(*)::int n from app.email_outbox where recipient_id=${citizen.id} and delivery_status='HELD'`)[0].n===2,'Previously queued receipts are held while disabled');
  await rejects(()=>web`select * from app.set_citizen_access(${owner.auth},${owner.provider},${owner.digest},${citizen.id},${before.revision},'ACTIVE','Review completed',${randomUUID()},${randomBytes(32)})`,'P0412','Stale Admin detail is rejected');
  await rejects(()=>web`select * from app.set_citizen_access(${owner.auth},${owner.provider},${owner.digest},${citizen.id},${after.revision},'ACTIVE',' ',${randomUUID()},${randomBytes(32)})`,'22023','Reactivation requires reason');
  const [enabled]=await web`select * from app.set_citizen_access(${owner.auth},${owner.provider},${owner.digest},${citizen.id},${after.revision},'ACTIVE','Review completed',${randomUUID()},${randomBytes(32)})`;
  check(enabled.access_status==='ACTIVE','Citizen reactivated');
  const [restored]=await admin`select * from app.application_profiles where id=${citizen.id}`;
  check(Number(restored.security_epoch)===Number(after.security_epoch),'Reactivation never reduces epoch');
  check((await web`select * from app.resolve_application_session(${citizen.auth},${citizen.provider},${citizen.digest},false)`)[0].state!=='VALID','Old session remains unusable');
  check((await web`select * from app.create_application_session(${citizen.auth},${randomUUID()},${randomBytes(32)},'CITIZEN')`).length===1,'Fresh login can create a new session');
  check((await admin`select count(*)::int n from app.notifications where complaint_id=${complaintBefore.id} and recipient_id=${citizen.id}`)[0].n===1,'Reactivation does not backfill missed notifications');
  check((await admin`select count(*)::int n from app.email_outbox where recipient_id=${citizen.id} and delivery_status='HELD'`)[0].n===2,'Reactivation does not automatically release held emails');
  const history=await web`select * from app.read_citizen_status_audit(${owner.auth},${owner.provider},${owner.digest},${citizen.id})`;
  check(history.length===2&&history.every(row=>row.reason&&row.change_summary.security_epoch),'Both transitions retain reason and audit evidence');
  check((await admin`select count(*)::int n from app.legal_acknowledgements where citizen_id=${citizen.id}`)[0].n===2,'Legal acknowledgement evidence preserved');
  const secondAdmin=await make('ADMIN'),contended=await make('CITIZEN');
  const [contendedProfile]=await admin`select revision from app.application_profiles where id=${contended.id}`;
  const contenders=[owner,secondAdmin].map(staff=>web`select * from app.set_citizen_access(${staff.auth},${staff.provider},${staff.digest},${contended.id},${contendedProfile.revision},'DISABLED','Concurrent administrative review',${randomUUID()},${randomBytes(32)})`);
  const outcomes=await Promise.allSettled(contenders);
  check(outcomes.filter(result=>result.status==='fulfilled').length===1&&outcomes.filter(result=>result.status==='rejected'&&(result.reason as {code?:string}).code==='P0412').length===1,'Concurrent Admin disables serialize to one transition');
  check((await admin`select count(*)::int n from app.audit_events where resource_type='APPLICATION_PROFILE' and resource_id=${contended.id} and action='ACCOUNT_DISABLED'`)[0].n===1,'Concurrent commands create one disable audit event');
  const blocked=await make('CITIZEN');
  const [blockedProfile]=await admin`select revision from app.application_profiles where id=${blocked.id}`;
  let release!:()=>void,markStarted!:()=>void;
  const gate=new Promise<void>(resolve=>{release=resolve;});
  const started=new Promise<void>(resolve=>{markStarted=resolve;});
  const held=web.begin(async tx=>{
   await tx`select * from app.set_citizen_access(${owner.auth},${owner.provider},${owner.digest},${blocked.id},${blockedProfile.revision},'DISABLED','Serialized access review',${randomUUID()},${randomBytes(32)})`;
   markStarted();await gate;
  });
  await started;
  let settled=false;
  const pending=Promise.resolve(web`select * from app.submit_complaint(${blocked.auth},${blocked.provider},${blocked.digest},${randomUUID()},${randomBytes(32)},${categoryId},${locationId},'Blocked complaint','This Citizen submission waits for the account decision.',null,true)`);
  pending.finally(()=>{settled=true;}).catch(()=>{});
  await new Promise(resolve=>setTimeout(resolve,150));
  check(!settled,'Citizen submission waits behind Admin profile lock');
  release();await held;
  await rejects(()=>pending,'42501','Citizen submission cannot commit after disable wins lock');
  console.log(`DEV-10 database: ${passed} checks passed.`);
 }finally{await mailer.end();await web.end();await admin.end();}
}
