import {publisherLabel} from '@/features/content-admin/presentation';
import {randomUUID} from 'node:crypto';
import {notFound} from 'next/navigation';
import {requireAdmin} from '@/server/auth/application-user';
import {readAdminPage,readAdminPageHistory} from '@/server/content-admin/repository';
import {PageEditor} from '@/features/content-admin/components';
import {contentAdminCopy,pageNames} from '@/features/content-admin/copy';
import {pageKeySchema,pageRoutes} from '@/features/public-content/model';
import type {ContentAdminLocale} from '@/features/content-admin/model';
import {Link} from '@/shared/i18n/navigation';
export default async function Page({params}:{params:Promise<{locale:ContentAdminLocale;pageKey:string}>}){const {locale,pageKey}=await params,parsed=pageKeySchema.safeParse(pageKey);if(!parsed.success)notFound();const actor=await requireAdmin(locale),[page,history]=await Promise.all([readAdminPage(actor,parsed.data),readAdminPageHistory(actor,parsed.data)]);if(!page)notFound();const c=contentAdminCopy[locale],publicRoute='/'+pageRoutes[page.key];return <section className="content-detail"><div className="content-detail-heading"><div><span className="eyebrow">{c.pages}</span><h1>{pageNames[locale][page.key]}</h1></div><Link className="btn ghost" href={publicRoute}>{c.openPublic}</Link></div><div className="commune-card publication-meta"><strong>{c.current}: {c.version} {page.currentVersion}</strong><span>{c.published}: {new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short'}).format(page.publishedAt)}</span><span>{c.publisher}: {publisherLabel(locale,page.publisherName,page.actorType)}</span></div><PageEditor key={page.revision} page={page} commandKey={randomUUID()}/><section className="commune-card publication-history"><h2>{c.history}</h2>{history.length?history.map(item=><details key={item.id}><summary><span>{c.version} {item.version}{item.current?` — ${c.current}`:` — ${c.previous}`}</span><small>{new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short'}).format(item.publishedAt)} · {publisherLabel(locale,item.publisherName,item.actorType)}</small></summary><div className="history-translations">{(['ar','fr','en'] as const).map(language=><article key={language} lang={language} dir={language==='ar'?'rtl':'ltr'}><strong>{c[{ar:'arabic',fr:'french',en:'english'}[language] as 'arabic'|'french'|'english']}</strong><h3>{item.translations[language].title}</h3><p>{item.translations[language].body}</p></article>)}</div></details>):<p>{c.noHistory}</p>}</section></section>;}
