import {randomUUID} from 'node:crypto';
import {notFound} from 'next/navigation';
import {requireCitizen} from '@/server/auth/application-user';
import {ownComplaint,ownComplaintHistory} from '@/server/complaints/repository';
import {referencePattern} from '@/features/complaints/model';
import {complaintCopy} from '@/features/complaints/copy';
import {ComplaintFacts} from '@/features/complaints/components/detail';
import {ComplaintTimeline,StatusBadge} from '@/features/complaints/components/tracking';
import {ConfirmAction} from '@/features/complaints/components/confirm-action';
import {withdrawComplaintAction} from '@/features/complaints/actions';
import {trackingCopy} from '@/features/complaints/tracking-copy';
import {Link} from '@/shared/i18n/navigation';
export const metadata={title:'Complaint',robots:{index:false,follow:false}};
export default async function Page({params,searchParams}:{params:Promise<{locale:'ar'|'fr'|'en';reference:string}>;searchParams:Promise<{state?:string}>}){const {locale,reference}=await params,actor=await requireCitizen(locale,true);if(!referencePattern.test(reference))notFound();const [complaint,history,state]=await Promise.all([ownComplaint(actor,reference),ownComplaintHistory(actor,reference),searchParams]);if(!complaint)notFound();const c=complaintCopy[locale],t=trackingCopy[locale];return <section className="complaint-page"><span className="eyebrow">{c.detail}</span><h1><bdi dir="ltr">{complaint.reference}</bdi></h1>{state.state&&<p className={`form-result ${state.state==='conflict'?'error':''}`} role="status">{state.state==='edited'?t.saved:state.state==='withdrawn'?t.withdrawn:state.state==='conflict'?t.conflict:''}</p>}<div className="complaint-panel"><div className="detail-status"><StatusBadge locale={locale} status={complaint.status}/></div><ComplaintFacts locale={locale} values={complaint}/><p>{t.submitted}: <time dateTime={complaint.submitted_at.toISOString()}>{new Intl.DateTimeFormat(locale,{dateStyle:'long',timeStyle:'short',timeZone:'Africa/Casablanca'}).format(complaint.submitted_at)}</time></p><p>{t.updated}: <time dateTime={complaint.updated_at.toISOString()}>{new Intl.DateTimeFormat(locale,{dateStyle:'long',timeStyle:'short',timeZone:'Africa/Casablanca'}).format(complaint.updated_at)}</time></p></div>{complaint.status==='SUBMITTED'&&<div className="complaint-actions"><Link className="btn ghost" href={`/citizen/complaints/${reference}/edit`}>{t.edit}</Link><ConfirmAction action={withdrawComplaintAction} title={t.withdraw} message={t.withdrawConfirm} cancel={t.cancel} hidden={{locale,reference,expectedRevision:complaint.revision,commandKey:randomUUID()}}>{t.withdraw}</ConfirmAction></div>}<ComplaintTimeline locale={locale} events={history}/><Link href="/citizen/complaints" className="btn ghost">{t.title}</Link></section>;}
