import type {ComplaintStatus} from './model';
const statuses:Record<'ar'|'fr'|'en',Record<ComplaintStatus,string>>={
 ar:{SUBMITTED:'تم الاستلام',UNDER_REVIEW:'قيد الدراسة',IN_PROCESSING:'قيد المعالجة',RESPONSE_SENT:'تم إرسال الجواب',CLOSED:'مغلقة',WITHDRAWN:'تم السحب',NOT_ACCEPTED:'غير مقبولة'},
 fr:{SUBMITTED:'Reçue',UNDER_REVIEW:'En cours d’examen',IN_PROCESSING:'En traitement',RESPONSE_SENT:'Réponse envoyée',CLOSED:'Clôturée',WITHDRAWN:'Retirée',NOT_ACCEPTED:'Non acceptée'},
 en:{SUBMITTED:'Received',UNDER_REVIEW:'Under review',IN_PROCESSING:'In processing',RESPONSE_SENT:'Response sent',CLOSED:'Closed',WITHDRAWN:'Withdrawn',NOT_ACCEPTED:'Not accepted'}
};
export const trackingCopy={
 ar:{title:'شكاياتي',inbox:'الشكايات',dashboard:'لوحة القيادة',newComplaint:'إضافة شكاية',search:'البحث بالرقم المرجعي أو الموضوع',staffSearch:'البحث بالرقم أو الموضوع أو اسم المواطن',filter:'الحالة',location:'الموقع',all:'الكل',apply:'تطبيق',empty:'لا توجد شكايات.',noResults:'لا توجد نتائج مطابقة.',details:'عرض التفاصيل',loadMore:'عرض المزيد',previous:'السابق',next:'التالي',page:'الصفحة',of:'من',go:'انتقال',submitted:'تاريخ الإيداع',updated:'آخر تحديث',status:'الحالة',subject:'الموضوع',category:'الفئة',citizen:'المواطن',history:'سجل الشكاية',edited:'تم تعديل معلومات الشكاية',stateChanged:'تم تغيير حالة الشكاية',edit:'تعديل الشكاية',save:'حفظ التعديلات',withdraw:'سحب الشكاية',cancel:'إلغاء',withdrawConfirm:'هل تؤكد سحب هذه الشكاية؟ لا يمكن التراجع عن هذا الإجراء.',startReview:'بدء الدراسة',reviewConfirm:'هل تريد بدء دراسة هذه الشكاية؟',contact:'بيانات المواطن',email:'البريد الإلكتروني',phone:'الهاتف',none:'غير متوفر',conflict:'تغيرت الشكاية منذ فتح الصفحة. أعد تحميلها قبل المحاولة.',saved:'تم حفظ التعديلات.',withdrawn:'تم سحب الشكاية.',reviewing:'بدأت دراسة الشكاية.',received:'تم إيداع الشكاية'},
 fr:{title:'Mes réclamations',inbox:'Réclamations',dashboard:'Tableau de bord',newComplaint:'Ajouter une réclamation',search:'Rechercher par référence ou objet',staffSearch:'Rechercher par référence, objet ou citoyen',filter:'Statut',location:'Lieu',all:'Tous',apply:'Appliquer',empty:'Aucune réclamation.',noResults:'Aucun résultat correspondant.',details:'Voir les détails',loadMore:'Afficher plus',previous:'Précédent',next:'Suivant',page:'Page',of:'sur',go:'Aller',submitted:'Date de dépôt',updated:'Dernière mise à jour',status:'Statut',subject:'Objet',category:'Catégorie',citizen:'Citoyen',history:'Historique de la réclamation',edited:'Informations de la réclamation modifiées',stateChanged:'Statut de la réclamation modifié',edit:'Modifier la réclamation',save:'Enregistrer les modifications',withdraw:'Retirer la réclamation',cancel:'Annuler',withdrawConfirm:'Confirmez-vous le retrait ? Cette action est définitive.',startReview:'Commencer l’examen',reviewConfirm:'Commencer l’examen de cette réclamation ?',contact:'Coordonnées du citoyen',email:'E-mail',phone:'Téléphone',none:'Non renseigné',conflict:'La réclamation a changé depuis l’ouverture de la page. Rechargez-la.',saved:'Modifications enregistrées.',withdrawn:'Réclamation retirée.',reviewing:'L’examen de la réclamation a commencé.',received:'Réclamation déposée'},
 en:{title:'My complaints',inbox:'Complaints',dashboard:'Dashboard',newComplaint:'Add complaint',search:'Search by reference or subject',staffSearch:'Search by reference, subject, or Citizen',filter:'Status',location:'Location',all:'All',apply:'Apply',empty:'No complaints yet.',noResults:'No matching results.',details:'View details',loadMore:'Load more',previous:'Previous',next:'Next',page:'Page',of:'of',go:'Go',submitted:'Submitted',updated:'Last updated',status:'Status',subject:'Subject',category:'Category',citizen:'Citizen',history:'Complaint history',edited:'Complaint information edited',stateChanged:'Complaint status changed',edit:'Edit complaint',save:'Save changes',withdraw:'Withdraw complaint',cancel:'Cancel',withdrawConfirm:'Withdraw this complaint? This action cannot be undone.',startReview:'Start review',reviewConfirm:'Start reviewing this complaint?',contact:'Citizen contact',email:'Email',phone:'Phone',none:'Not provided',conflict:'This complaint changed after you opened it. Reload before trying again.',saved:'Changes saved.',withdrawn:'Complaint withdrawn.',reviewing:'Complaint review started.',received:'Complaint submitted'}
} as const;
export function statusLabel(locale:'ar'|'fr'|'en',status:ComplaintStatus){return statuses[locale][status];}
