'use server';
import {revalidatePath} from 'next/cache';
import {redirect} from 'next/navigation';
import {requireAdmin} from '@/server/auth/application-user';
import {catalogueFingerprint} from '@/server/catalogues/fingerprint';
import {createCatalogue,updateCatalogue,setCatalogueActive} from '@/server/catalogues/repository';
import {createCatalogueSchema,updateCatalogueSchema,stateCatalogueSchema,type CatalogueAdminState} from './model';
const fail=(code:string):CatalogueAdminState=>({status:'error',code});
const errorCode=(error:unknown)=>{const code=typeof error==='object'&&error&&'code' in error?String(error.code):'';return code==='P0812'||code==='P0409'?'conflict':code==='P0801'||code==='P0802'?'incomplete':code==='23514'?'invalid':'failed';};
const fields=(form:FormData)=>({locale:form.get('locale'),kind:form.get('kind'),commandKey:form.get('commandKey'),arabic:form.get('arabic'),french:form.get('french'),english:form.get('english')});
export async function createCatalogueAction(_:CatalogueAdminState,form:FormData):Promise<CatalogueAdminState>{const parsed=createCatalogueSchema.safeParse(fields(form));if(!parsed.success)return fail('invalid');const value=parsed.data,actor=await requireAdmin(value.locale),canonical={kind:value.kind,ar:value.arabic,fr:value.french,en:value.english},fingerprint=catalogueFingerprint(`${value.kind}_CREATE`,canonical),plural=value.kind==='CATEGORY'?'categories':'locations';let id:string;try{const row=await createCatalogue(actor,{kind:value.kind,key:value.commandKey,fingerprint,ar:value.arabic,fr:value.french,en:value.english});id=row.id;revalidatePath(`/${value.locale}/commune/catalogues/${plural}`);}catch(error){return fail(errorCode(error));}redirect(`/${value.locale}/commune/catalogues/${plural}/${id}`);}
export async function updateCatalogueAction(_:CatalogueAdminState,form:FormData):Promise<CatalogueAdminState>{const parsed=updateCatalogueSchema.safeParse({...fields(form),id:form.get('id'),revision:form.get('revision')});if(!parsed.success)return fail('invalid');const value=parsed.data,actor=await requireAdmin(value.locale),canonical={id:value.id,revision:value.revision,ar:value.arabic,fr:value.french,en:value.english},fingerprint=catalogueFingerprint(`${value.kind}_UPDATE`,canonical),plural=value.kind==='CATEGORY'?'categories':'locations';try{await updateCatalogue(actor,{kind:value.kind,id:value.id,revision:value.revision,key:value.commandKey,fingerprint,ar:value.arabic,fr:value.french,en:value.english});revalidatePath(`/${value.locale}/commune/catalogues/${plural}`);revalidatePath(`/${value.locale}/commune/catalogues/${plural}/${value.id}`);return {status:'success',code:'success'};}catch(error){return fail(errorCode(error));}}
export async function setCatalogueStateAction(_:CatalogueAdminState,form:FormData):Promise<CatalogueAdminState>{const parsed=stateCatalogueSchema.safeParse({locale:form.get('locale'),kind:form.get('kind'),id:form.get('id'),revision:form.get('revision'),commandKey:form.get('commandKey'),active:form.get('active')});if(!parsed.success)return fail('invalid');const value=parsed.data,actor=await requireAdmin(value.locale),canonical={id:value.id,revision:value.revision,active:value.active},fingerprint=catalogueFingerprint(`${value.kind}_SET_ACTIVE`,canonical),plural=value.kind==='CATEGORY'?'categories':'locations';try{await setCatalogueActive(actor,{kind:value.kind,id:value.id,revision:value.revision,key:value.commandKey,fingerprint,active:value.active});revalidatePath(`/${value.locale}/commune/catalogues/${plural}`);revalidatePath(`/${value.locale}/commune/catalogues/${plural}/${value.id}`);return {status:'success',code:'success'};}catch(error){return fail(errorCode(error));}}

