'use client';
import {useActionState,useEffect,useRef,useState} from 'react';
import {useLocale} from 'next-intl';
import {useRouter} from '@/shared/i18n/navigation';
import {ConfirmationDialog} from '@/shared/ui/confirmation-dialog';
import {createCatalogueAction,setCatalogueStateAction,updateCatalogueAction} from './actions';
import {catalogueAdminCopy,type CatalogueAdminLocale} from './copy';
import {initialCatalogueAdminState,type CatalogueAdminItem,type CatalogueKind} from './model';
function Result({state}:{state:typeof initialCatalogueAdminState}){const locale=useLocale() as CatalogueAdminLocale,c=catalogueAdminCopy[locale];return state.code?<p className={`form-result ${state.status}`} role={state.status==='error'?'alert':'status'}>{c[state.code as keyof typeof c]??c.failed}</p>:null;}
export function CatalogueEditor({kind,item,commandKey}:{kind:CatalogueKind;item?:CatalogueAdminItem;commandKey:string}){const locale=useLocale() as CatalogueAdminLocale,c=catalogueAdminCopy[locale],router=useRouter(),[state,action,pending]=useActionState(item?updateCatalogueAction:createCatalogueAction,initialCatalogueAdminState);useEffect(()=>{if(state.status==='success')router.refresh();},[router,state.status]);return <form action={action} className="commune-form commune-card catalogue-editor" aria-busy={pending}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="kind" value={kind}/><input type="hidden" name="commandKey" value={commandKey}/>{item&&<><input type="hidden" name="id" value={item.id}/><input type="hidden" name="revision" value={item.revision}/></>}<label className="commune-field">{c.arabic}<input name="arabic" lang="ar" dir="rtl" defaultValue={item?.labels.ar??''} required maxLength={200}/></label><label className="commune-field">{c.french}<input name="french" lang="fr" dir="ltr" defaultValue={item?.labels.fr??''} required={Boolean(item?.labels.fr)} maxLength={200}/></label><label className="commune-field">{c.english}<input name="english" lang="en" dir="ltr" defaultValue={item?.labels.en??''} required={Boolean(item?.labels.en)} maxLength={200}/></label><Result state={state}/><button className="btn" disabled={pending}>{pending?c.pending:item?c.save:c.create}</button></form>}
export function CatalogueStateControl({kind,item,commandKey}:{kind:CatalogueKind;item:CatalogueAdminItem;commandKey:string}){const locale=useLocale() as CatalogueAdminLocale,c=catalogueAdminCopy[locale],[state,action,pending]=useActionState(setCatalogueStateAction,initialCatalogueAdminState),form=useRef<HTMLFormElement>(null),approved=useRef(false),[open,setOpen]=useState(false),activating=!item.isActive,label=activating?c.activate:c.deactivate;return <><form ref={form} action={action} className="catalogue-state-form" onSubmit={event=>{if(approved.current){approved.current=false;return;}event.preventDefault();setOpen(true);}}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="kind" value={kind}/><input type="hidden" name="id" value={item.id}/><input type="hidden" name="revision" value={item.revision}/><input type="hidden" name="commandKey" value={commandKey}/><input type="hidden" name="active" value={String(activating)}/><Result state={state}/><button className={`btn${activating?'':' danger'}`} disabled={pending}>{pending?c.pending:label}</button></form><ConfirmationDialog open={open} title={label} message={activating?c.activateConfirm:c.deactivateConfirm} confirmLabel={label} cancelLabel={c.cancel} danger={!activating} onCancel={()=>setOpen(false)} onConfirm={()=>{setOpen(false);approved.current=true;form.current?.requestSubmit();}}/></>}

