'use client';
import {useActionState,useEffect,useRef,useState} from 'react';
import {useLocale} from 'next-intl';
import {useRouter} from '@/shared/i18n/navigation';
import {ConfirmationDialog} from '@/shared/ui/confirmation-dialog';
import {parsePublicBody} from '@/features/public-content/markdown';
import {publishPageAction,updateSettingsAction} from './actions';
import {contentAdminCopy} from './copy';
import {contentAdminLocales,initialContentAdminState,type AdminPage,type AdminSettings,type ContentAdminLocale} from './model';

function Result({state}:{state:typeof initialContentAdminState}){const locale=useLocale() as ContentAdminLocale,c=contentAdminCopy[locale];return state.code?<p className={`form-result ${state.status}`} role={state.status==='error'?'alert':'status'}>{c[state.code as keyof typeof c]??c.failed}</p>:null;}
export function SafePreview({title,body,language}:{title:string;body:string;language:ContentAdminLocale}){const parsed=parsePublicBody(body);return <article className="content-preview" lang={language} dir={language==='ar'?'rtl':'ltr'}><h2>{title}</h2>{parsed.introduction.map((text,index)=><p key={`i-${index}`}>{text}</p>)}{parsed.sections.map((section,index)=><section key={`${section.heading}-${index}`}><h3>{section.heading}</h3>{section.paragraphs.map((text,item)=><p key={item}>{text}</p>)}</section>)}</article>;}
const labels={ar:'arabic',fr:'french',en:'english'} as const;
export function PageEditor({page,commandKey}:{page:AdminPage;commandKey:string}){
 const locale=useLocale() as ContentAdminLocale,c=contentAdminCopy[locale],router=useRouter(),[state,action,pending]=useActionState(publishPageAction,initialContentAdminState),form=useRef<HTMLFormElement>(null),approved=useRef(false),[open,setOpen]=useState(false),[previewLanguage,setPreviewLanguage]=useState<ContentAdminLocale>(locale),[values,setValues]=useState(page.translations);
 useEffect(()=>{if(state.status==='success')router.refresh();},[router,state.status]);const set=(language:ContentAdminLocale,field:'title'|'body',value:string)=>setValues(current=>({...current,[language]:{...current[language],[field]:value}}));
 return <><form ref={form} action={action} className="content-editor" aria-busy={pending} onSubmit={event=>{if(approved.current){approved.current=false;return;}event.preventDefault();setOpen(true);}}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="pageKey" value={page.key}/><input type="hidden" name="revision" value={page.revision}/><input type="hidden" name="commandKey" value={commandKey}/><div className="content-language-grid">{contentAdminLocales.map(language=><fieldset key={language} lang={language} dir={language==='ar'?'rtl':'ltr'}><legend>{c[labels[language]]}</legend><label>{c.titleLabel}<input name={`${language}Title`} value={values[language].title} onChange={event=>set(language,'title',event.target.value)} required maxLength={200}/></label><label>{c.bodyLabel}<textarea name={`${language}Body`} value={values[language].body} onChange={event=>set(language,'body',event.target.value)} required maxLength={30000}/></label></fieldset>)}</div><p className="field-help">{c.formatHelp}</p><section className="commune-card content-preview-panel"><div className="content-preview-heading"><h2>{c.preview}</h2><label>{c.previewLanguage}<select value={previewLanguage} onChange={event=>setPreviewLanguage(event.target.value as ContentAdminLocale)}>{contentAdminLocales.map(language=><option key={language} value={language}>{c[labels[language]]}</option>)}</select></label></div><SafePreview title={values[previewLanguage].title} body={values[previewLanguage].body} language={previewLanguage}/></section><Result state={state}/><button className="btn" disabled={pending}>{pending?c.pending:c.publish}</button></form><ConfirmationDialog open={open} title={c.publishTitle} message={c.publishConfirm} confirmLabel={c.publish} cancelLabel={c.cancel} onCancel={()=>setOpen(false)} onConfirm={()=>{setOpen(false);approved.current=true;form.current?.requestSubmit();}}/></>;
}
export function SettingsEditor({settings,commandKey}:{settings:AdminSettings;commandKey:string}){
 const locale=useLocale() as ContentAdminLocale,c=contentAdminCopy[locale],router=useRouter(),[state,action,pending]=useActionState(updateSettingsAction,initialContentAdminState),form=useRef<HTMLFormElement>(null),approved=useRef(false),[open,setOpen]=useState(false);
 useEffect(()=>{if(state.status==='success')router.refresh();},[router,state.status]);return <><form ref={form} action={action} className="content-editor settings-editor" aria-busy={pending} onSubmit={event=>{if(approved.current){approved.current=false;return;}event.preventDefault();setOpen(true);}}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="revision" value={settings.revision}/><input type="hidden" name="commandKey" value={commandKey}/><section className="commune-card settings-core"><label>{c.contactPhone}<input name="contactPhone" defaultValue={settings.contactPhone} dir="ltr" required maxLength={24}/></label><label>{c.contactEmail}<input name="contactEmail" defaultValue={settings.contactEmail} dir="ltr" type="email" required maxLength={254}/></label><label>{c.chikayaUrl}<select name="chikayaUrl" defaultValue={settings.chikayaUrl} dir="ltr"><option value="https://chikaya.ma/">https://chikaya.ma/</option><option value="https://www.chikaya.ma/">https://www.chikaya.ma/</option></select></label></section><div className="content-language-grid settings-languages">{contentAdminLocales.map(language=><fieldset key={language} lang={language} dir={language==='ar'?'rtl':'ltr'}><legend>{c[labels[language]]}</legend><label>{c.communeName}<input name={`${language}CommuneName`} defaultValue={settings.translations[language].commune_name} required maxLength={200}/></label><label>{c.address}<textarea name={`${language}PublicAddress`} defaultValue={settings.translations[language].public_address} required maxLength={1000}/></label><label>{c.hours}<textarea name={`${language}OpeningHours`} defaultValue={settings.translations[language].opening_hours} required maxLength={1000}/></label></fieldset>)}</div><Result state={state}/><button className="btn" disabled={pending}>{pending?c.saving:c.saveSettings}</button></form><ConfirmationDialog open={open} title={c.settingsTitle} message={c.settingsConfirm} confirmLabel={c.saveSettings} cancelLabel={c.cancel} onCancel={()=>setOpen(false)} onConfirm={()=>{setOpen(false);approved.current=true;form.current?.requestSubmit();}}/></>;
}
