'use client';
import {useActionState,useState} from 'react';
import {useLocale} from 'next-intl';
import {Eye,EyeSlash} from '@phosphor-icons/react';
import {changeEmailAction,changePasswordAction,updateProfileAction} from '@/features/auth/actions';
import {initialAuthState,type AuthState} from '@/features/auth/model';

type Locale='ar'|'fr'|'en';
const copy={
 ar:{name:'الاسم الكامل',phone:'رقم الهاتف (اختياري)',email:'البريد الإلكتروني',language:'اللغة المفضلة',save:'حفظ التغييرات',current:'كلمة المرور الحالية',password:'كلمة المرور الجديدة',confirmation:'تأكيد كلمة المرور',changePassword:'تغيير كلمة المرور',newEmail:'البريد الإلكتروني الجديد',changeEmail:'إرسال رابط التأكيد',success:'تم حفظ التغيير.',emailSent:'أرسلنا رابط تأكيد واحداً إلى البريد الجديد. سيبقى بريدك الحالي معتمداً إلى أن تؤكد البريد الجديد.',error:'تعذر حفظ التغيير. تحقق من المعلومات أو أعد تحميل الصفحة.',passwordLength:'يجب أن تتكون كلمة المرور من 10 أحرف على الأقل.',passwordObvious:'اختر كلمة مرور يصعب تخمينها.',passwordMismatch:'كلمتا المرور غير متطابقتين.',reauthenticationFailed:'كلمة المرور الحالية غير صحيحة.',pending:'جار الحفظ…',show:'إظهار',hide:'إخفاء'},
 fr:{name:'Nom complet',phone:'Téléphone (facultatif)',email:'Adresse courriel',language:'Langue préférée',save:'Enregistrer',current:'Mot de passe actuel',password:'Nouveau mot de passe',confirmation:'Confirmer le mot de passe',changePassword:'Modifier le mot de passe',newEmail:'Nouvelle adresse courriel',changeEmail:'Envoyer le lien de confirmation',success:'Modification enregistrée.',emailSent:'Un seul lien de confirmation a été envoyé à la nouvelle adresse. L’adresse actuelle reste valide jusqu’à la confirmation.',error:'Impossible d’enregistrer. Vérifiez les informations ou rechargez la page.',passwordLength:'Le mot de passe doit contenir au moins 10 caractères.',passwordObvious:'Choisissez un mot de passe difficile à deviner.',passwordMismatch:'Les mots de passe ne correspondent pas.',reauthenticationFailed:'Le mot de passe actuel est incorrect.',pending:'Enregistrement…',show:'Afficher',hide:'Masquer'},
 en:{name:'Full name',phone:'Phone (optional)',email:'Email address',language:'Preferred language',save:'Save changes',current:'Current password',password:'New password',confirmation:'Confirm password',changePassword:'Change password',newEmail:'New email address',changeEmail:'Send confirmation link',success:'Change saved.',emailSent:'We sent one confirmation link to the new address. Your current email remains active until the new address is verified.',error:'Unable to save. Check the information or reload the page.',passwordLength:'Use at least 10 characters.',passwordObvious:'Choose a password that is harder to guess.',passwordMismatch:'The passwords do not match.',reauthenticationFailed:'The current password is incorrect.',pending:'Saving…',show:'Show',hide:'Hide'}
};
function Password({name,label,value,onChange}:{name:string;label:string;value:string;onChange:(value:string)=>void}){const locale=useLocale() as Locale,c=copy[locale];const [show,setShow]=useState(false);return <div className="field"><label htmlFor={name}><b>{label}</b></label><div className="password"><input id={name} name={name} type={show?'text':'password'} autoComplete={name==='currentPassword'?'current-password':'new-password'} required minLength={name==='currentPassword'?undefined:10} value={value} onChange={event=>onChange(event.target.value)}/><button type="button" aria-label={show?c.hide:c.show} aria-pressed={show} onClick={()=>setShow(!show)}>{show?<EyeSlash size={20}/>:<Eye size={20}/>}</button></div></div>}
function Result({state,initialSuccess=false}:{state:AuthState;initialSuccess?:boolean}){const c=copy[useLocale() as Locale];if(state.status==='idle'&&!initialSuccess)return null;const success=state.status==='success'||initialSuccess;const text=state.code==='emailChangeSent'?c.emailSent:state.code==='passwordLength'?c.passwordLength:state.code==='passwordObvious'?c.passwordObvious:state.code==='passwordMismatch'?c.passwordMismatch:state.code==='reauthenticationFailed'?c.reauthenticationFailed:success?c.success:c.error;return <p className={`form-result ${success?'success':'error'}`} role={success?'status':'alert'}>{text}</p>}
export function ProfileForm({profile,saved=false}:{profile:{fullName:string;phone:string|null;email:string;language:Locale;revision:number};saved?:boolean}){const locale=useLocale() as Locale,c=copy[locale];const [state,action,pending]=useActionState(updateProfileAction,initialAuthState);const [fullName,setFullName]=useState(profile.fullName),[phone,setPhone]=useState(profile.phone??''),[language,setLanguage]=useState<Locale>(profile.language);return <form action={action} className="account-form" onReset={event=>event.preventDefault()}><Result state={state} initialSuccess={saved}/><label className="field"><b>{c.name}</b><input name="fullName" value={fullName} onChange={event=>setFullName(event.target.value)} autoComplete="name" required maxLength={200}/></label><label className="field"><b>{c.email}</b><input value={profile.email} readOnly dir="ltr" aria-readonly="true"/></label><label className="field"><b>{c.phone}</b><input name="phone" value={phone} onChange={event=>setPhone(event.target.value)} autoComplete="tel" dir="ltr" maxLength={24}/></label><label className="field"><b>{c.language}</b><select name="language" value={language} onChange={event=>setLanguage(event.target.value as Locale)}><option value="ar">العربية</option><option value="fr">Français</option><option value="en">English</option></select></label><input type="hidden" name="revision" value={profile.revision}/><button className="btn" type="submit" disabled={pending}>{pending?c.pending:c.save}</button></form>}
export function PasswordForm(){const locale=useLocale() as Locale,c=copy[locale];const [state,action,pending]=useActionState(changePasswordAction,initialAuthState);const [currentPassword,setCurrentPassword]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState('');return <form action={action} className="account-form" onReset={event=>event.preventDefault()}><Result state={state}/><input type="hidden" name="locale" value={locale}/><Password name="currentPassword" label={c.current} value={currentPassword} onChange={setCurrentPassword}/><Password name="password" label={c.password} value={password} onChange={setPassword}/><Password name="confirmation" label={c.confirmation} value={confirmation} onChange={setConfirmation}/><button className="btn" type="submit" disabled={pending}>{pending?c.pending:c.changePassword}</button></form>}
export function EmailForm({email}:{email:string}){const locale=useLocale() as Locale,c=copy[locale];const [state,action,pending]=useActionState(changeEmailAction,initialAuthState);const [newEmail,setNewEmail]=useState(''),[currentPassword,setCurrentPassword]=useState('');return <form action={action} className="account-form" onReset={event=>event.preventDefault()}><Result state={state}/><input type="hidden" name="locale" value={locale}/><label className="field"><b>{c.email}</b><input value={email} readOnly dir="ltr"/></label><label className="field"><b>{c.newEmail}</b><input name="email" type="email" autoComplete="email" required dir="ltr" value={newEmail} onChange={event=>setNewEmail(event.target.value)} suppressHydrationWarning/></label><Password name="currentPassword" label={c.current} value={currentPassword} onChange={setCurrentPassword}/><button className="btn" type="submit" disabled={pending}>{pending?c.pending:c.changeEmail}</button></form>}
