import 'server-only';
import {publicDatabase} from '@/shared/db/public';
import type {ApplicationUser} from '@/server/auth/application-user';
import {adminPublicationBundleSchema,adminSettingsBundleSchema,type AdminPage,type AdminPageHistory,type AdminPageSummary,type AdminSettings,type AdminSettingsHistory,type ContentAdminLocale} from '@/features/content-admin/model';
import type {PageKey} from '@/features/public-content/model';
const number=(value:unknown)=>Number(value);
export async function listAdminPages(actor:ApplicationUser,locale:ContentAdminLocale):Promise<AdminPageSummary[]>{return (await publicDatabase()`select * from app.list_admin_public_pages(${actor.authUserId},${actor.providerSessionId},${actor.digest},${locale})`).map(row=>({id:String(row.page_id),key:String(row.page_key) as PageKey,currentVersion:number(row.current_version),revision:number(row.revision),title:String(row.title),publishedAt:new Date(row.published_at)}));}
export async function readAdminPage(actor:ApplicationUser,key:PageKey):Promise<AdminPage|null>{const [row]=await publicDatabase()`select * from app.read_admin_public_page(${actor.authUserId},${actor.providerSessionId},${actor.digest},${key})`;return row?{id:String(row.page_id),key:String(row.page_key) as PageKey,currentVersion:number(row.current_version),revision:number(row.revision),translations:adminPublicationBundleSchema.parse(row.translations),publishedAt:new Date(row.published_at),publisherName:row.publisher_name?String(row.publisher_name):null,actorType:String(row.actor_type)}:null;}
export async function readAdminPageHistory(actor:ApplicationUser,key:PageKey):Promise<AdminPageHistory[]>{return (await publicDatabase()`select * from app.read_admin_public_page_history(${actor.authUserId},${actor.providerSessionId},${actor.digest},${key},${30})`).map(row=>({id:String(row.version_id),version:number(row.version_number),current:Boolean(row.is_current),translations:adminPublicationBundleSchema.parse(row.translations),publishedAt:new Date(row.published_at),publisherName:row.publisher_name?String(row.publisher_name):null,actorType:String(row.actor_type)}));}
export async function publishAdminPage(actor:ApplicationUser,input:{key:PageKey;revision:number;commandKey:string;fingerprint:Buffer;bundle:unknown}){const sql=publicDatabase();const [row]=await sql`select * from app.publish_public_page(${actor.authUserId},${actor.providerSessionId},${actor.digest},${input.key},${input.revision},${input.commandKey},${input.fingerprint},${sql.json(input.bundle as never)})`;return row;}
export async function readAdminSettings(actor:ApplicationUser):Promise<AdminSettings|null>{const [row]=await publicDatabase()`select * from app.read_admin_commune_settings(${actor.authUserId},${actor.providerSessionId},${actor.digest})`;return row?{id:String(row.settings_id),contactPhone:String(row.contact_phone),contactEmail:String(row.contact_email),chikayaUrl:String(row.chikaya_url),revision:number(row.revision),updatedAt:new Date(row.updated_at),translations:adminSettingsBundleSchema.parse(row.translations)}:null;}
export async function readAdminSettingsHistory(actor:ApplicationUser):Promise<AdminSettingsHistory[]>{return (await publicDatabase()`select * from app.read_admin_commune_settings_history(${actor.authUserId},${actor.providerSessionId},${actor.digest},${30})`).map(row=>({revision:number(row.revision),changedFields:Array.isArray(row.changed_fields)?row.changed_fields.map(String):[],occurredAt:new Date(row.occurred_at),publisherName:row.publisher_name?String(row.publisher_name):null}));}
export async function updateAdminSettings(actor:ApplicationUser,input:{revision:number;commandKey:string;fingerprint:Buffer;phone:string;email:string;chikayaUrl:string;bundle:unknown}){const sql=publicDatabase();const [row]=await sql`select * from app.update_commune_settings(${actor.authUserId},${actor.providerSessionId},${actor.digest},${input.revision},${input.commandKey},${input.fingerprint},${input.phone},${input.email},${input.chikayaUrl},${sql.json(input.bundle as never)})`;return row;}
