import {randomUUID} from 'node:crypto';
import type {ComplaintStatus,ResponseVersion} from '../model';
import {canClose,canCorrectResponse,canNotAccept,canRespond,canStartProcessing} from '../model';
import {lifecycleCopy} from '../lifecycle-copy';
import {ConfirmAction} from './confirm-action';
import {closeComplaintAction,correctResponseAction,issueResponseAction,notAcceptAction,startProcessingAction} from '../actions';

const Hidden=({locale,reference,revision}:{locale:string;reference:string;revision:number})=><><input type="hidden" name="locale" value={locale}/><input type="hidden" name="reference" value={reference}/><input type="hidden" name="expectedRevision" value={revision}/><input type="hidden" name="commandKey" value={randomUUID()}/></>;
export function ResponseHistory({locale,versions,rejectionReason}:{locale:'ar'|'fr'|'en';versions:ResponseVersion[];rejectionReason?:'OUT_OF_SCOPE'|'INSUFFICIENT_INFORMATION'|null}){if(!versions.length)return null;const c=lifecycleCopy[locale];return <section className="response-card"><h2>{c.response}</h2>{rejectionReason&&<p className="rejection-reason"><strong>{c.notAcceptReason}:</strong> {rejectionReason==='OUT_OF_SCOPE'?c.outOfScope:c.insufficient}</p>}{versions.map((item,index)=><article key={item.versionNumber} className={index===0?'is-current':''}><header><strong>{item.responseKind==='NOT_ACCEPTED'?c.notAccepted:c.normal}</strong><span>{c.version} {item.versionNumber}</span></header><p dir="auto">{item.body}</p>{item.correctionReason&&<p className="response-reason"><strong>{c.correctionReason}:</strong> <span dir="auto">{item.correctionReason}</span></p>}<time dateTime={item.createdAt.toISOString()}>{new Intl.DateTimeFormat(locale,{dateStyle:'long',timeStyle:'short',timeZone:'Africa/Casablanca'}).format(item.createdAt)}</time></article>)}</section>;}

export function LifecycleControls({locale,reference,revision,status,latest}:{locale:'ar'|'fr'|'en';reference:string;revision:number;status:ComplaintStatus;latest?:ResponseVersion}){const c=lifecycleCopy[locale];return <section className="lifecycle-controls" aria-label={c.response}>
 {canStartProcessing(status)&&<ConfirmAction action={startProcessingAction} title={c.startProcessing} message={c.processingConfirm} cancel={c.cancel} danger={false} hidden={{locale,reference,expectedRevision:revision,commandKey:randomUUID()}}>{c.startProcessing}</ConfirmAction>}
 {canRespond(status)&&<form action={issueResponseAction} className="lifecycle-form"><h2>{c.sendResponse}</h2><Hidden locale={locale} reference={reference} revision={revision}/><label>{c.responseBody}<textarea name="body" required maxLength={2000}/></label><label className="complaint-confirm"><input type="checkbox" name="confirmed" value="true" required/>{c.confirmResponse}</label><button className="btn" type="submit">{c.sendResponse}</button></form>}
 {canNotAccept(status)&&<form action={notAcceptAction} className="lifecycle-form"><h2>{c.notAccept}</h2><Hidden locale={locale} reference={reference} revision={revision}/><label>{c.notAcceptReason}<select name="reason" required defaultValue=""><option value="" disabled>—</option><option value="OUT_OF_SCOPE">{c.outOfScope}</option><option value="INSUFFICIENT_INFORMATION">{c.insufficient}</option></select></label><label>{c.explanation}<textarea name="body" required maxLength={2000}/></label><label className="complaint-confirm"><input type="checkbox" name="confirmed" value="true" required/>{c.confirmResponse}</label><button className="btn danger" type="submit">{c.notAccept}</button></form>}
 {canCorrectResponse(status)&&latest&&<form action={correctResponseAction} className="lifecycle-form"><h2>{c.correct}</h2><Hidden locale={locale} reference={reference} revision={revision}/><label>{c.newBody}<textarea name="body" required maxLength={2000} defaultValue={latest.body}/></label><label>{c.correctionReason}<textarea name="correctionReason" required maxLength={500}/></label><label>{c.currentPassword}<input name="currentPassword" type="password" required autoComplete="current-password" maxLength={2048}/></label><p className="form-help">{c.reauthHelp}</p><label className="complaint-confirm"><input type="checkbox" name="confirmed" value="true" required/>{c.confirmCorrection}</label><button className="btn" type="submit">{c.correct}</button></form>}
 {canClose(status)&&<ConfirmAction action={closeComplaintAction} title={c.close} message={c.closeConfirm} cancel={c.cancel} hidden={{locale,reference,expectedRevision:revision,commandKey:randomUUID()}}>{c.close}</ConfirmAction>}
 </section>;}
