import {randomUUID} from 'node:crypto';
import {notFound,redirect} from 'next/navigation';
import {requireCitizen} from '@/server/auth/application-user';
import {ownComplaint} from '@/server/complaints/repository';
import {readCitizenEditCatalogues} from '@/server/catalogues/repository';
import {referencePattern,sortedCatalogue,catalogueLabel} from '@/features/complaints/model';
import {editComplaintAction} from '@/features/complaints/actions';
import {complaintCopy} from '@/features/complaints/copy';
import {trackingCopy} from '@/features/complaints/tracking-copy';
import {catalogueAdminCopy} from '@/features/catalogue-admin/copy';
import {inactiveOptionLabel} from '@/features/catalogue-admin/model';
export const metadata={title:'Edit complaint',robots:{index:false,follow:false}};
export default async function Page({params,searchParams}:{params:Promise<{locale:'ar'|'fr'|'en';reference:string}>;searchParams:Promise<{state?:string}>}){const {locale,reference}=await params,actor=await requireCitizen(locale,true);if(!referencePattern.test(reference))notFound();const [complaint,catalogues,state]=await Promise.all([ownComplaint(actor,reference),readCitizenEditCatalogues(actor,reference),searchParams]);if(!complaint)notFound();if(complaint.status!=='SUBMITTED')redirect(`/${locale}/citizen/complaints/${reference}?state=conflict`);const c=complaintCopy[locale],t=trackingCopy[locale],inactive=catalogueAdminCopy[locale].inactive;return <section className="complaint-page"><span className="eyebrow">{t.title}</span><h1>{t.edit}</h1>{state.state&&<p className="form-result error" role="alert">{state.state==='conflict'?t.conflict:c.validation}</p>}<form className="complaint-panel" action={editComplaintAction}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="reference" value={reference}/><input type="hidden" name="expectedRevision" value={complaint.revision}/><input type="hidden" name="commandKey" value={randomUUID()}/><label>{c.category}<select name="categoryId" defaultValue={complaint.category_id} required>{sortedCatalogue(catalogues.categories,locale).map(item=>{const label=catalogueLabel(item,locale);return <option key={item.id} value={item.id} lang={label.language}>{item.isActive?label.text:inactiveOptionLabel(label.text,inactive)}</option>;})}</select></label><label>{c.subject}<input name="subject" defaultValue={complaint.subject} maxLength={150} required/></label><label>{c.description}<textarea name="description" defaultValue={complaint.description} minLength={20} maxLength={2000} required/></label><label>{c.location}<select name="locationId" defaultValue={complaint.location_id} required>{sortedCatalogue(catalogues.locations,locale).map(item=>{const label=catalogueLabel(item,locale);return <option key={item.id} value={item.id} lang={label.language}>{item.isActive?label.text:inactiveOptionLabel(label.text,inactive)}</option>;})}</select></label><label>{c.clarification}<input name="locationClarification" defaultValue={complaint.location_clarification??''} maxLength={300}/></label><div className="complaint-buttons"><button className="btn" type="submit">{t.save}</button></div></form></section>;}
