'use client';
import Image from 'next/image';
import {useActionState,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {ArrowRight,Eye,EyeSlash,ShieldCheck,SignIn} from '@phosphor-icons/react';
import {Link} from '@/shared/i18n/navigation';
import {confirmEmailAction,completeRegistrationAction,loginAction,recoveryAction,resendVerificationAction,resetPasswordAction,signupAction} from '@/features/auth/actions';
import {initialAuthState,type AuthState} from '@/features/auth/model';
import {designLabels} from '../design-labels';

type Locale='ar'|'fr'|'en';type Mode='login'|'register'|'recovery'|'resend'|'verify'|'reset'|'complete';
type Legal={termsVersionId:string;privacyVersionId:string}|null;
const copy={
 ar:{login:'تسجيل الدخول',register:'إنشاء حساب مواطن',recovery:'استعادة كلمة المرور',verify:'تأكيد البريد الإلكتروني',reset:'اختيار كلمة مرور جديدة',complete:'إكمال التسجيل',lead:'ادخل إلى فضائك الخاص.',registerLead:'أنشئ حساباً خاصاً وآمناً.',name:'الاسم الكامل',email:'البريد الإلكتروني',phone:'رقم الهاتف (اختياري)',password:'كلمة المرور',confirm:'تأكيد كلمة المرور',show:'إظهار كلمة المرور',hide:'إخفاء كلمة المرور',forgot:'نسيت كلمة المرور؟',send:'إرسال رابط الاستعادة',agree:'أوافق على',and:'و',submit:'متابعة',have:'لديك حساب؟',noAccount:'ليس لديك حساب؟',verifyLead:'هذه ليست خطوة تسجيل ثانية. لحماية رابطك من الفحص الآلي، اضغط زر تأكيد البريد أدناه. لا تحتاج إلى إدخال أي معلومات.',verifySubmit:'تأكيد البريد الإلكتروني'},
 fr:{login:'Connexion',register:'Créer un compte citoyen',recovery:'Récupérer le mot de passe',verify:'Confirmer l’adresse courriel',reset:'Choisir un nouveau mot de passe',complete:'Terminer l’inscription',lead:'Accédez à votre espace privé.',registerLead:'Créez un compte privé et sécurisé.',name:'Nom complet',email:'Adresse courriel',phone:'Téléphone (facultatif)',password:'Mot de passe',confirm:'Confirmer le mot de passe',show:'Afficher le mot de passe',hide:'Masquer le mot de passe',forgot:'Mot de passe oublié ?',send:'Envoyer le lien',agree:'J’accepte les',and:'et la',submit:'Continuer',have:'Vous avez un compte ?',noAccount:'Vous n’avez pas de compte ?',verifyLead:'Ce n’est pas une deuxième inscription. Pour protéger le lien des scanners automatiques, confirmez votre adresse ci-dessous. Aucune information n’est à saisir.',verifySubmit:'Confirmer le courriel'},
 en:{login:'Sign in',register:'Create a citizen account',recovery:'Recover your password',verify:'Confirm your email',reset:'Choose a new password',complete:'Complete registration',lead:'Access your private Citizen space.',registerLead:'Create a private and secure account.',name:'Full name',email:'Email address',phone:'Phone (optional)',password:'Password',confirm:'Confirm password',show:'Show password',hide:'Hide password',forgot:'Forgot password?',send:'Send recovery link',agree:'I agree to the',and:'and',submit:'Continue',have:'Already have an account?',noAccount:'Don’t have an account?',verifyLead:'This is not a second registration. To protect the link from automated scanners, confirm your email below. You do not need to enter any information.',verifySubmit:'Confirm email'}
};
const messages:Record<Locale,Record<string,string>>={
 ar:{confirmReady:'لا تحتاج إلى إدخال أي معلومات. اضغط زر تأكيد البريد الإلكتروني لإكمال التحقق.',verificationResent:'إذا كان الحساب ينتظر التأكيد فستصل رسالة جديدة.',idle:'أدخل المعلومات المطلوبة.',validation:'تحقق من الحقول المطلوبة.',passwordLength:'يجب أن تتكون كلمة المرور من 10 أحرف على الأقل.',passwordObvious:'اختر كلمة مرور يصعب تخمينها.',passwordTooLong:'كلمة المرور طويلة جداً.',passwordMismatch:'كلمتا المرور غير متطابقتين.',phoneInvalid:'رقم الهاتف غير صالح.',invalidCredentials:'تعذر تسجيل الدخول. تحقق من المعلومات وتأكيد البريد.',accountUnavailable:'الحساب غير متاح.',recoverySent:'إذا كان الحساب موجوداً فستصل رسالة الاستعادة.',linkInvalid:'الرابط غير صالح أو منتهي أو سبق استعماله. اطلب رسالة جديدة أو سجل الدخول إذا سبق تأكيد حسابك.',authenticationRequired:'يلزم تسجيل الدخول أو إعادة فتح الرابط.',legalChanged:'تم تحديث الشروط. راجعها ثم أعد المحاولة.',operationFailed:'لم يتم تأكيد العملية. حاول مجدداً.',passwordReset:'تم تغيير كلمة المرور. سجل الدخول من جديد.'},
 fr:{confirmReady:'Aucune information n’est requise. Cliquez sur Confirmer le courriel pour terminer.',verificationResent:'Si le compte attend une confirmation, un nouveau courriel sera envoyé.',idle:'Saisissez les informations demandées.',validation:'Vérifiez les champs requis.',passwordLength:'Le mot de passe doit contenir au moins 10 caractères.',passwordObvious:'Choisissez un mot de passe difficile à deviner.',passwordTooLong:'Le mot de passe est trop long.',passwordMismatch:'Les mots de passe ne correspondent pas.',phoneInvalid:'Le numéro de téléphone est invalide.',invalidCredentials:'Connexion impossible. Vérifiez vos informations et la confirmation du courriel.',accountUnavailable:'Le compte est indisponible.',recoverySent:'Si le compte existe, un courriel de récupération sera envoyé.',linkInvalid:'Le lien est invalide, expiré ou déjà utilisé. Demandez un nouveau message ou connectez-vous si le compte est déjà confirmé.',authenticationRequired:'Une authentification ou le lien original est requis.',legalChanged:'Les documents ont changé. Relisez-les puis réessayez.',operationFailed:'L’opération n’a pas été confirmée. Réessayez.',passwordReset:'Mot de passe modifié. Connectez-vous à nouveau.'},
 en:{confirmReady:'No information is required. Select Confirm email to finish verification.',verificationResent:'If the account is awaiting confirmation, a new email will be sent.',idle:'Enter the required information.',validation:'Check the required fields.',passwordLength:'Use at least 10 characters.',passwordObvious:'Choose a password that is harder to guess.',passwordTooLong:'The password is too long.',passwordMismatch:'The passwords do not match.',phoneInvalid:'The phone number is invalid.',invalidCredentials:'Unable to sign in. Check your details and email confirmation.',accountUnavailable:'The account is unavailable.',recoverySent:'If the account exists, a recovery email will be sent.',linkInvalid:'The link is invalid, expired, or already used. Request a new email or sign in if the account is already verified.',authenticationRequired:'Authentication or the original link is required.',legalChanged:'The legal documents changed. Review them and try again.',operationFailed:'The operation was not confirmed. Try again.',passwordReset:'Password changed. Sign in again.'}
};
function Password({name='password',label,current=false,value,onChange}:{name?:string;label:string;current?:boolean;value:string;onChange:(value:string)=>void}){const locale=useLocale() as Locale,c=copy[locale];const [show,setShow]=useState(false);return <div className="field"><label htmlFor={name}><b>{label}</b></label><div className="password"><input id={name} name={name} type={show?'text':'password'} autoComplete={current?'current-password':'new-password'} required minLength={current?undefined:10} value={value} onChange={event=>onChange(event.target.value)}/><button type="button" aria-label={show?c.hide:c.show} aria-pressed={show} onClick={()=>setShow(!show)}>{show?<EyeSlash size={20}/>:<Eye size={20}/>}</button></div></div>}
function Status({state,fallback}:{state:AuthState;fallback?:string}){const locale=useLocale() as Locale,code=state.code??fallback??'idle';return <p className={`auth-notice ${state.status==='error'?'error-notice':''}`} role={state.status==='error'?'alert':'status'} tabIndex={-1}>{messages[locale][code]??messages[locale].idle}</p>}
export function AuthPage({mode,legal,state:initialState,returnTo}:{mode:Mode;legal?:Legal;state?:string;returnTo?:string}){
 const locale=useLocale() as Locale,t=useTranslations(),c=copy[locale],d=designLabels[locale];const action=mode==='login'?loginAction:mode==='register'?signupAction:mode==='complete'?completeRegistrationAction:mode==='recovery'?recoveryAction:mode==='resend'?resendVerificationAction:mode==='reset'?resetPasswordAction:confirmEmailAction;const [state,formAction,pending]=useActionState(action,initialAuthState);const [values,setValues]=useState({fullName:'',phone:'',email:'',password:'',confirmation:'',accepted:false});const set=(key:keyof typeof values,value:string|boolean)=>setValues(current=>({...current,[key]:value}));const title=mode==='resend'?copy[locale].verify:c[mode],lead=mode==='verify'?c.verifyLead:mode==='register'||mode==='complete'?c.registerLead:c.lead;
 return <div className="auth"><div className="auth-box"><section><Link className="back" href="/"><ArrowRight className="direction-arrow" size={18}/>{t('back')}</Link><span className="eyebrow">{t('brand')}</span><h1>{title}</h1><p>{lead}</p><Status state={state} fallback={initialState??(mode==='verify'?'confirmReady':undefined)}/><form action={formAction} noValidate onReset={event=>event.preventDefault()}><input type="hidden" name="locale" value={locale}/>{mode==='login'&&returnTo&&<input type="hidden" name="returnTo" value={returnTo}/>}
 {(mode==='register'||mode==='complete')&&<><label className="field"><b>{c.name}</b><input name="fullName" autoComplete="name" required maxLength={200} value={values.fullName} onChange={event=>set('fullName',event.target.value)}/></label><label className="field"><b>{c.phone}</b><input name="phone" type="tel" dir="ltr" autoComplete="tel" maxLength={24} value={values.phone} onChange={event=>set('phone',event.target.value)}/></label></>}
 {['login','register','recovery','resend'].includes(mode)&&<label className="field"><b>{c.email}</b><input name="email" type="email" dir="ltr" autoComplete="email" required maxLength={320} value={values.email} onChange={event=>set('email',event.target.value)} suppressHydrationWarning/></label>}
 {mode==='login'&&<Password label={c.password} current value={values.password} onChange={value=>set('password',value)}/>}{mode==='register'&&<Password label={c.password} value={values.password} onChange={value=>set('password',value)}/>}
 {mode==='login'&&<Link className="link" href="/forgot-password">{c.forgot}</Link>}
 {mode==='reset'&&<><Password label={c.password} value={values.password} onChange={value=>set('password',value)}/><Password name="confirmation" label={c.confirm} value={values.confirmation} onChange={value=>set('confirmation',value)}/></>}
 {(mode==='register'||mode==='complete')&&legal&&<><input type="hidden" name="termsVersionId" value={legal.termsVersionId}/><input type="hidden" name="privacyVersionId" value={legal.privacyVersionId}/><label className="check"><input name="accepted" type="checkbox" required checked={values.accepted} onChange={event=>set('accepted',event.target.checked)}/><span>{c.agree} <Link href="/terms" target="_blank" rel="noopener">{t('nav.TERMS')}</Link> {c.and} <Link href="/privacy" target="_blank" rel="noopener">{t('nav.PRIVACY')}</Link></span></label></>}
 <button className="btn" type="submit" disabled={pending||((mode==='register'||mode==='complete')&&!legal)}><SignIn size={20}/>{pending?'…':mode==='verify'?c.verifySubmit:mode==='recovery'||mode==='resend'?c.send:c.submit}</button></form>{(mode==='login'||mode==='register')&&<p className="switch">{mode==='login'?c.noAccount:c.have} <Link className="link" href={mode==='login'?'/register':'/login'}>{mode==='login'?t('createAccount'):t('signIn')}</Link></p>}{(mode==='resend'||(mode==='verify'&&state.status==='error'))&&<p className="switch"><Link className="link" href="/login">{t('signIn')}</Link></p>}</section><aside><Image src="/assets/abaynou-architecture-transparent.webp" width={650} height={390} alt={d.alt} unoptimized/><div><ShieldCheck size={27}/><h2>{d.privacy}</h2><p>{d.privacyText}</p></div></aside></div></div>;
}
