'use client';
import Image from 'next/image';
import {useRef,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {ArrowRight,Eye,EyeSlash,ShieldCheck,SignIn} from '@phosphor-icons/react';
import {Link} from '@/shared/i18n/navigation';
import {designLabels} from '../design-labels';
const copy={
 ar:{login:'تسجيل الدخول',register:'إنشاء حساب مواطن',recovery:'استعادة كلمة المرور',welcome:'مرحباً بعودتك',start:'ابدأ التواصل',lead:'ادخل إلى فضائك الخاص لمتابعة شكاياتك.',registerLead:'أنشئ حساباً بسيطاً لتقديم شكاياتك ومتابعتها.',recoveryLead:'استعمل البريد الإلكتروني المرتبط بحسابك.',name:'الاسم الكامل',email:'البريد الإلكتروني',phone:'رقم الهاتف (اختياري)',password:'كلمة المرور',show:'إظهار كلمة المرور',hide:'إخفاء كلمة المرور',forgot:'نسيت كلمة المرور؟',send:'إرسال رابط الاستعادة',agree:'أوافق على',and:'و',verify:'يُؤكد البريد الإلكتروني مرة واحدة عند التسجيل.',notice:'هذه معاينة للواجهات. خدمة الحسابات لم تُفعّل بعد؛ لا تُرسل أو تُحفظ البيانات المدخلة.',unavailable:'خدمة الحسابات غير متاحة بعد. لم يتم إرسال أو حفظ أي معلومات.',have:'لديك حساب بالفعل؟',noAccount:'ليس لديك حساب؟'},
 fr:{login:'Connexion',register:'Créer un compte citoyen',recovery:'Récupérer le mot de passe',welcome:'Heureux de vous retrouver',start:'Commencez votre démarche',lead:'Accédez à votre espace privé pour suivre vos réclamations.',registerLead:'Un compte simple pour déposer et suivre vos réclamations.',recoveryLead:'Utilisez le courriel associé à votre compte.',name:'Nom complet',email:'Adresse courriel',phone:'Téléphone (facultatif)',password:'Mot de passe',show:'Afficher le mot de passe',hide:'Masquer le mot de passe',forgot:'Mot de passe oublié ?',send:'Envoyer le lien',agree:'J’accepte les',and:'et la',verify:'Le courriel est vérifié une fois lors de l’inscription.',notice:'Aperçu des interfaces. Le service de comptes n’est pas encore activé ; les données saisies ne sont ni transmises ni enregistrées.',unavailable:'Le service de comptes est indisponible. Aucune information n’a été envoyée ou enregistrée.',have:'Vous avez déjà un compte ?',noAccount:'Vous n’avez pas de compte ?'},
 en:{login:'Sign in',register:'Create a citizen account',recovery:'Recover your password',welcome:'Welcome back',start:'Start connecting',lead:'Sign in to your private space to track your complaints.',registerLead:'A simple account to submit and follow your complaints.',recoveryLead:'Use the email address associated with your account.',name:'Full name',email:'Email address',phone:'Phone (optional)',password:'Password',show:'Show password',hide:'Hide password',forgot:'Forgot password?',send:'Send recovery link',agree:'I agree to the',and:'and',verify:'Email is verified once at registration.',notice:'Interface preview. Account services are not yet enabled; entered data is neither sent nor stored.',unavailable:'Account services are unavailable. No information was sent or stored.',have:'Already have an account?',noAccount:'Don’t have an account?'}
};
export function AuthPage({mode}:{mode:'login'|'register'|'recovery'}){
 const locale=useLocale() as keyof typeof copy,t=useTranslations(),c=copy[locale],d=designLabels[locale];const [show,setShow]=useState(false),[submitted,setSubmitted]=useState(false);const notice=useRef<HTMLParagraphElement>(null);
 return <div className="auth"><div className="auth-box"><section><Link className="back" href="/"><ArrowRight className="direction-arrow" size={18} aria-hidden="true"/>{t('back')}</Link><span className="eyebrow">{mode==='login'?c.welcome:c.start}</span><h1>{c[mode]}</h1><p>{mode==='login'?c.lead:mode==='register'?c.registerLead:c.recoveryLead}</p><p className="auth-notice" id="auth-notice" role="status" tabIndex={-1} ref={notice}>{submitted?c.unavailable:c.notice}</p>
 <form aria-describedby="auth-notice" onSubmit={e=>{e.preventDefault();setSubmitted(true);notice.current?.focus();}}>
 {mode==='register'&&<label className="field"><b>{c.name}</b><input name="name" autoComplete="name" required maxLength={120}/></label>}
 <label className="field"><b>{c.email}</b><input name="email" type="email" dir="ltr" autoComplete="email" required/></label>
 {mode==='register'&&<label className="field"><b>{c.phone}</b><input name="phone" type="tel" dir="ltr" autoComplete="tel"/></label>}
 {mode!=='recovery'&&<div className="field"><label htmlFor="password"><b>{c.password}</b></label><div className="password"><input id="password" name="password" type={show?'text':'password'} autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='register'?8:undefined}/><button type="button" aria-label={show?c.hide:c.show} aria-pressed={show} onClick={()=>setShow(!show)}>{show?<EyeSlash size={20}/>:<Eye size={20}/>}</button></div></div>}
 {mode==='login'&&<Link className="link" href="/forgot-password">{c.forgot}</Link>}
 {mode==='register'&&<><p className="verification-note">{c.verify}</p><label className="check"><input type="checkbox" required/><span>{c.agree} <Link href="/terms">{t('nav.TERMS')}</Link> {c.and} <Link href="/privacy">{t('nav.PRIVACY')}</Link></span></label></>}
 <button className="btn" type="submit"><SignIn size={20} aria-hidden="true"/>{mode==='recovery'?c.send:c[mode]}</button></form>
 <p className="switch">{mode==='login'?c.noAccount:c.have} <Link className="link" href={mode==='login'?'/register':'/login'}>{mode==='login'?t('createAccount'):t('signIn')}</Link></p></section><aside><Image src="/assets/abaynou-architecture-transparent.webp" width={650} height={390} alt={d.alt} unoptimized/><div><ShieldCheck size={27} aria-hidden="true"/><h2>{d.privacy}</h2><p>{d.privacyText}</p></div></aside></div></div>;
}
