import Image from 'next/image';
import {getLocale,getTranslations} from 'next-intl/server';
import {ShieldCheck,NotePencil,MapPin,ClipboardText,Buildings,WarningCircle,Info,Plus,CaretLeft,Question,CheckCircle,Clock,Gear,UserCircle,Phone,EnvelopeSimple,Check} from '@phosphor-icons/react/dist/ssr';
import {Link} from '@/shared/i18n/navigation';
import {Callout} from '@/shared/ui/primitives';
import {parsePublicBody,type ContentSection} from '../markdown';
import {type PublicPage,type PublicSettings,type PageKey} from '../model';
import {designLabels} from '../design-labels';
const locations=['دوار أباينو','دوار ايكيسل','دوار توتلين','دوار أبوقال','دوار إد العربا','دوار تبولوت'];
const topicIcons=[ClipboardText,NotePencil,MapPin,Buildings,WarningCircle,Info];
function Paragraphs({items}:{items:string[]}){return <>{items.map((text,i)=><p key={i}>{text}</p>)}</>;}
function SectionTitle({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="section-title"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>;}
function Topics({sections,full=false}:{sections:ContentSection[];full?:boolean}){return <div className={full?'category-grid':'topic-grid'}>{sections.map((s,i)=>{const Icon=topicIcons[i%topicIcons.length];return <article key={s.heading}><span><Icon size={24} aria-hidden="true"/></span><h3>{s.heading}</h3><Paragraphs items={s.paragraphs}/></article>;})}</div>;}
export async function PublicPageView({page,pageKey,settings,scopePage}:{page:PublicPage;pageKey:PageKey;settings:PublicSettings|null;processPage?:PublicPage|null;scopePage?:PublicPage|null}){
 const t=await getTranslations(),locale=await getLocale(),c=designLabels[locale as keyof typeof designLabels]??designLabels.ar;const content=parsePublicBody(page.body);
 const action=<div className="page-action"><Link className="btn" href="/register"><Plus size={20} aria-hidden="true"/>{c.start}</Link></div>;
 const privacy=<div className="assurance"><ShieldCheck size={28} aria-hidden="true"/><span><b>{c.privacy}</b><small>{c.privacyText}</small></span></div>;
 if(pageKey==='HOME')return <>
  <section className="public-hero"><div><span className="eyebrow">{c.eyebrow}</span><h1>{page.title}</h1><Paragraphs items={content.introduction}/><div className="actions"><Link className="btn" href="/register"><Plus size={20} aria-hidden="true"/>{c.start}</Link><Link className="btn secondary" href="/how-it-works">{c.learn}</Link></div><small className="trust"><ShieldCheck size={20} aria-hidden="true"/>{c.trust}</small></div><Image className="hero-illustration" src="/assets/abaynou-architecture-transparent.webp" alt={c.alt} width={650} height={390} priority unoptimized/><Image className="hero-zellige" src="/assets/zellige-edge-transparent.webp" width={175} height={430} alt="" unoptimized/></section>
  <section className="principles" aria-label={c.principles}>{content.sections.slice(0,3).map((s,i)=>{const Icon=[ShieldCheck,NotePencil,MapPin][i];return <div key={s.heading}><Icon size={28} aria-hidden="true"/><span><b>{s.heading}</b><small>{s.paragraphs.join(' ')}</small></span></div>;})}</section>
  <section className="how"><SectionTitle eyebrow={c.steps} title={c.how} text={c.howLead}/><div className="steps">{content.sections.slice(3,6).map((s,i)=>{const Icon=[NotePencil,MapPin,ClipboardText][i];return <article className="step" key={s.heading}><span><Icon size={26} aria-hidden="true"/></span><i aria-hidden="true">0{i+1}</i><h3>{s.heading}</h3><Paragraphs items={s.paragraphs}/></article>;})}</div><div className="section-link"><Link className="link" href="/how-it-works">{c.allSteps}<CaretLeft className="direction-arrow" size={18} aria-hidden="true"/></Link></div></section>
  <section className="home-scope"><SectionTitle eyebrow={c.scope} title={c.topics} text={c.topicsLead}/>{scopePage&&<Topics sections={parsePublicBody(scopePage.body).sections.slice(0,4)}/>}<div className="scope-note-wide"><Info size={26} aria-hidden="true"/><span><b>{c.scopeTitle}</b><small>{c.scopeNote}</small></span><Link className="link" href="/service-scope">{c.scopeLink}<CaretLeft className="direction-arrow" size={18} aria-hidden="true"/></Link></div></section>
  <section className="follow-up"><SectionTitle eyebrow={c.follow} title={c.after} text={c.afterLead}/><ol className="status-journey">{content.sections.slice(6,10).map((s,i)=>{const Icon=[CheckCircle,Clock,Gear,ShieldCheck][i];return <li key={s.heading}><span><Icon size={20} aria-hidden="true"/></span><div><b>{s.heading}</b><small>{s.paragraphs.join(' ')}</small></div></li>;})}</ol></section>
  <section className="home-help"><div><Question size={29} aria-hidden="true"/><span><b>{c.help}</b><small>{c.helpText}</small></span></div><div><Link className="btn secondary" href="/faq">{t('nav.FAQ')}</Link><Link className="link" href="/contact">{t('nav.CONTACT')}<CaretLeft className="direction-arrow" size={18} aria-hidden="true"/></Link></div></section>
 </>;
 return <div className="info-page"><div className="intro"><span className="eyebrow">{t('brand')}</span><h1>{page.title}</h1><Paragraphs items={content.introduction}/></div>
 {pageKey==='HOW_IT_WORKS'&&<><section className="process-list">{content.sections.slice(0,5).map((s,i)=>{const Icon=[UserCircle,NotePencil,MapPin,CheckCircle,ClipboardText][i];return <article key={s.heading}><i aria-hidden="true">0{i+1}</i><span><Icon size={25} aria-hidden="true"/></span><div><h2>{s.heading}</h2><Paragraphs items={s.paragraphs}/></div></article>;})}</section><section className="info-columns">{content.sections.slice(5).map(s=><article key={s.heading}><h2>{s.heading}</h2>{s===content.sections[6]?<><ul className="status-list">{s.paragraphs[0]?.split(/←|→/).map((p,i)=><li key={p}><span aria-hidden="true" className={`dot ${['blue','amber','green','green','slate'][i]??'green'}`}/>{p.trim()}</li>)}</ul><Paragraphs items={s.paragraphs.slice(1)}/></>:<ul className="check-list">{s.paragraphs.map(p=><li key={p}><Check size={18} aria-hidden="true"/><span>{p}</span></li>)}</ul>}</article>)}</section>{privacy}{action}</>}
 {pageKey==='SERVICE_SCOPE'&&<><section className="category-section"><h2>{c.categories}</h2><Topics sections={content.sections.slice(0,6)} full/></section><section className="eligibility-grid">{content.sections.slice(6,8).map((s,i)=><article key={s.heading}>{i===0?<CheckCircle size={28} aria-hidden="true"/>:<Info size={28} aria-hidden="true"/>}<h2>{s.heading}</h2><ul>{s.paragraphs.map(p=><li key={p}>{p}</li>)}</ul></article>)}</section><div className="emergency-note"><WarningCircle size={29} aria-hidden="true"/><span><b>{c.emergency}</b><small>{c.emergencyText}</small></span></div><section className="decision-box"><div><span className="eyebrow">{c.before}</span><h2>{c.questions}</h2></div><ol>{c.decision.map((q,i)=><li key={q}><b>0{i+1}</b><span>{q}</span></li>)}</ol></section><section className="location-list"><h2>{c.locations}</h2><ul dir="rtl" lang="ar">{locations.map(l=><li key={l}>{l}</li>)}</ul></section>{action}</>}
 {pageKey==='FAQ'&&<><div className="faq-intro"><Info size={27} aria-hidden="true"/><span><b>{c.faqTitle}</b><small>{c.faqText}</small></span></div><div className="faq">{content.sections.map((s,i)=><details key={s.heading} open={i===0}><summary>{s.heading}<Plus size={20} aria-hidden="true"/></summary><div><Paragraphs items={s.paragraphs}/></div></details>)}</div><section className="faq-contact"><div><Question size={28} aria-hidden="true"/><span><b>{c.noAnswer}</b><small>{c.contactHelp}</small></span></div><Link className="btn secondary" href="/contact">{t('nav.CONTACT')}</Link></section></>}
 {pageKey==='CONTACT'&&(settings?<div className="contact">
 <div><Phone size={28} aria-hidden="true"/><span><small>{t('contact.phone')}</small>{settings.contact_phone?<a dir="ltr" href={'tel:'+settings.contact_phone.replace(/[ ()-]/g,'')}>{settings.contact_phone}</a>:<b>{t('contact.missing')}</b>}</span></div>
 <div><EnvelopeSimple size={28} aria-hidden="true"/><span><small>{t('contact.email')}</small>{settings.contact_email?<a dir="ltr" href={'mailto:'+settings.contact_email}>{settings.contact_email}</a>:<b>{t('contact.missing')}</b>}</span></div>
 <div><Clock size={28} aria-hidden="true"/><span><small>{t('contact.hours')}</small><b>{settings.opening_hours??t('contact.missing')}</b></span></div><div><MapPin size={28} aria-hidden="true"/><span><small>{t('contact.address')}</small><b>{settings.public_address??t('contact.missing')}</b></span></div>
 </div>:<Callout>{t('settingsMissing')}</Callout>)}
 {['USER_GUIDE','PRIVACY','TERMS','ACCESSIBILITY'].includes(pageKey)&&<article className="prose">{content.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2><Paragraphs items={s.paragraphs}/></section>)}<Link className="link" href="/contact">{t('nav.CONTACT')}<CaretLeft className="direction-arrow" size={18} aria-hidden="true"/></Link></article>}
 </div>;
}
