import {requireCitizen} from '@/server/auth/application-user';
import {listOwnComplaints} from '@/server/complaints/repository';
import {complaintListQuerySchema,complaintStatuses} from '@/features/complaints/model';
import {ComplaintList} from '@/features/complaints/components/tracking';
import {statusLabel,trackingCopy} from '@/features/complaints/tracking-copy';
import {Link} from '@/shared/i18n/navigation';
import {Plus} from '@phosphor-icons/react/dist/ssr';
export const metadata={title:'My complaints',robots:{index:false,follow:false}};
export default async function Page({params,searchParams}:{params:Promise<{locale:'ar'|'fr'|'en'}>;searchParams:Promise<Record<string,string|undefined>>}){const {locale}=await params,actor=await requireCitizen(locale,true),raw=await searchParams,parsed=complaintListQuerySchema.safeParse(raw),query=parsed.success?parsed.data:{q:'',status:''},items=await listOwnComplaints(actor,query),c=trackingCopy[locale],last=items.at(-1);const next=new URLSearchParams();if(query.q)next.set('q',query.q);if(query.status)next.set('status',query.status);if(last&&items.length===20){next.set('beforeTime',last.submitted_at.toISOString());next.set('beforeReference',last.reference);}return <section className="tracking-page"><div className="tracking-heading"><div><span className="eyebrow">{c.dashboard}</span><h1>{c.title}</h1></div><Link className="btn tracking-create" href="/citizen/complaints/new"><Plus size={19} aria-hidden="true"/>{c.newComplaint}</Link></div><form className="tracking-filters"><label>{c.search}<input name="q" defaultValue={query.q}/></label><label>{c.filter}<select name="status" defaultValue={query.status}><option value="">{c.all}</option>{complaintStatuses.map(status=><option key={status} value={status}>{statusLabel(locale,status)}</option>)}</select></label><button className="btn" type="submit">{c.apply}</button></form>{items.length?<ComplaintList locale={locale} items={items}/>:<div className="tracking-empty">{query.q||query.status?c.noResults:c.empty}</div>}{last&&items.length===20&&<Link className="btn ghost tracking-more" href={`/citizen/complaints?${next}`}>{c.loadMore}</Link>}</section>;}
