import {describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {canonicalComplaint,catalogueLabel,codePoints,complaintCommandSchema,complaintFieldsSchema,sortedCatalogue,canCitizenChange,canStartReview,complaintListQuerySchema,complaintResponseSchema,complaintNotAcceptedSchema,complaintCorrectionSchema,canStartProcessing,canRespond,canNotAccept,canCorrectResponse,canClose} from '../../src/features/complaints/model';
const input=()=>({categoryId:randomUUID(),locationId:randomUUID(),subject:' Original subject ',description:' Original description with sufficient text. ',locationClarification:''});
describe('complaint validation and preservation',()=>{
 it('counts astral characters as single code points',()=>{expect(codePoints('أ😀e\u0301')).toBe(4);expect(complaintFieldsSchema.safeParse({...input(),subject:'😀'.repeat(150)}).success).toBe(true);expect(complaintFieldsSchema.safeParse({...input(),subject:'😀'.repeat(151)}).success).toBe(false);});
 it('rejects blank subjects and short effective descriptions',()=>{expect(complaintFieldsSchema.safeParse({...input(),subject:'\u00a0\uFEFF\n'}).success).toBe(false);expect(complaintFieldsSchema.safeParse({...input(),description:'  '+'أ'.repeat(19)+'  '}).success).toBe(false);});
 it('enforces original rather than trimmed maximums',()=>{expect(complaintFieldsSchema.safeParse({...input(),subject:' '+'a'.repeat(150)}).success).toBe(false);expect(complaintFieldsSchema.safeParse({...input(),description:'😀'.repeat(2000)}).success).toBe(true);expect(complaintFieldsSchema.safeParse({...input(),description:'😀'.repeat(2001)}).success).toBe(false);});
 it('preserves authored whitespace, markup and combining characters',()=>{const value={...input(),subject:' <test> e\u0301 ',locationClarification:'  جنب المسجد  '};expect(canonicalComplaint(complaintFieldsSchema.parse(value))).toEqual(value);});
 it('maps only blank clarification to null',()=>{expect(canonicalComplaint({...input(),locationClarification:'\t\u00a0'}).locationClarification).toBeNull();expect(complaintFieldsSchema.safeParse({...input(),locationClarification:'😀'.repeat(301)}).success).toBe(false);});
 it('rejects text PostgreSQL cannot represent',()=>{for(const subject of ['a\0b','a\uD800b'])expect(complaintFieldsSchema.safeParse({...input(),subject}).success).toBe(false);});
 it('rejects injected authority and requires explicit confirmation',()=>{const value={...input(),commandKey:randomUUID(),locale:'ar',confirmed:true};expect(complaintCommandSchema.safeParse(value).success).toBe(true);expect(complaintCommandSchema.safeParse({...value,citizen_id:randomUUID()}).success).toBe(false);expect(complaintCommandSchema.safeParse({...value,confirmed:false}).success).toBe(false);});
 it('uses Arabic fallback without invented translations',()=>{expect(catalogueLabel({labels:{ar:'دوار أباينو'}},'fr')).toEqual({text:'دوار أباينو',language:'ar'});});
 it('sorts displayed labels with deterministic code ties',()=>{const items=[{id:'2',code:'B',labels:{ar:'ب',en:'Same'}},{id:'1',code:'A',labels:{ar:'أ',en:'Same'}}];expect(sortedCatalogue(items,'en').map(item=>item.code)).toEqual(['A','B']);expect(items[0].code).toBe('B');});
 it('freezes DEV-05 action eligibility at SUBMITTED',()=>{expect(canCitizenChange('SUBMITTED')).toBe(true);expect(canStartReview('SUBMITTED')).toBe(true);for(const status of ['UNDER_REVIEW','WITHDRAWN','IN_PROCESSING','RESPONSE_SENT','CLOSED','NOT_ACCEPTED'] as const){expect(canCitizenChange(status)).toBe(false);expect(canStartReview(status)).toBe(false);}});
 it('accepts bounded simple list criteria and rejects internal cursors',()=>{expect(complaintListQuerySchema.parse({q:'طريق',status:'UNDER_REVIEW'})).toMatchObject({q:'طريق',status:'UNDER_REVIEW'});expect(complaintListQuerySchema.safeParse({beforeReference:'not-a-reference'}).success).toBe(false);expect(complaintListQuerySchema.safeParse({q:'x'.repeat(151)}).success).toBe(false);});
 it('validates response, rejection, correction text, and explicit confirmation',()=>{const base={reference:'AB-2345-6789-ABCD',expectedRevision:2,commandKey:randomUUID(),body:'😀'.repeat(2000),confirmed:'true' as const};expect(complaintResponseSchema.safeParse(base).success).toBe(true);expect(complaintResponseSchema.safeParse({...base,confirmed:undefined}).success).toBe(false);expect(complaintResponseSchema.safeParse({...base,body:'😀'.repeat(2001)}).success).toBe(false);expect(complaintNotAcceptedSchema.safeParse({...base,reason:'DUPLICATE'}).success).toBe(false);expect(complaintCorrectionSchema.safeParse({...base,correctionReason:'x'.repeat(500),currentPassword:'private'}).success).toBe(true);expect(complaintCorrectionSchema.safeParse({...base,correctionReason:'x'.repeat(501),currentPassword:'private'}).success).toBe(false);});
 it('exposes only the frozen DEV-06 actions for each lifecycle state',()=>{expect(canStartProcessing('UNDER_REVIEW')).toBe(true);expect(canRespond('IN_PROCESSING')).toBe(true);expect(canNotAccept('UNDER_REVIEW')).toBe(true);expect(canNotAccept('IN_PROCESSING')).toBe(true);expect(canClose('RESPONSE_SENT')).toBe(true);for(const status of ['RESPONSE_SENT','CLOSED','NOT_ACCEPTED'] as const)expect(canCorrectResponse(status)).toBe(true);expect(canCorrectResponse('IN_PROCESSING')).toBe(false);expect(canClose('NOT_ACCEPTED')).toBe(false);});
});
