import 'server-only';
import {pendingStaffActivationEmails} from '@/server/auth/staff-admin-provider';
import {publicDatabase} from '@/shared/db/public';
import type {ApplicationUser} from '@/server/auth/application-user';
export type StaffAccount={profile_id:string;full_name:string;email:string;contact_phone:string|null;preferred_language:'ar'|'fr'|'en';role:'AGENT'|'ADMIN';access_status:'ACTIVE'|'DISABLED';revision:number;created_at:Date;updated_at?:Date;email_confirmed_at:Date|null;last_sign_in_at:Date|null;activation_pending?:boolean;total_count?:number};
const map=(r:Record<string,unknown>):StaffAccount=>({...r,revision:Number(r.revision),created_at:new Date(r.created_at as string),updated_at:r.updated_at?new Date(r.updated_at as string):undefined,email_confirmed_at:r.email_confirmed_at?new Date(r.email_confirmed_at as string):null,last_sign_in_at:r.last_sign_in_at?new Date(r.last_sign_in_at as string):null,total_count:r.total_count===undefined?undefined:Number(r.total_count)}) as StaffAccount;
export async function listStaff(actor:ApplicationUser,q:{query?:string;role?:string;status?:string;page:number},limit=20){const rows=await publicDatabase()`select * from app.list_staff_accounts(${actor.authUserId},${actor.providerSessionId},${actor.digest},${q.query||null},${q.role||null},${q.status||null},${q.page},${limit})`;const pending=await pendingStaffActivationEmails();return {items:rows.map(r=>({...map(r),activation_pending:pending.has(String(r.email).toLowerCase())})),total:rows[0]?Number(rows[0].total_count):0};}
export async function staffDetail(actor:ApplicationUser,id:string){const [r]=await publicDatabase()`select * from app.read_staff_account(${actor.authUserId},${actor.providerSessionId},${actor.digest},${id})`;if(!r)return null;const pending=await pendingStaffActivationEmails();return {...map(r),activation_pending:pending.has(String(r.email).toLowerCase())};}
export async function staffAudit(actor:ApplicationUser,id:string){return publicDatabase()`select * from app.read_staff_audit(${actor.authUserId},${actor.providerSessionId},${actor.digest},${id},${30})`;}
export async function provisionAgent(actor:ApplicationUser,input:{authId:string;email:string;name:string;phone?:string;language:string}){const [r]=await publicDatabase()`select app.provision_agent_profile(${actor.authUserId},${actor.providerSessionId},${actor.digest},${input.authId},${input.email},${input.name},${input.phone||null},${input.language}) id`;return r.id as string;}
export async function updateAgent(actor:ApplicationUser,input:{id:string;revision:number;name:string;phone?:string;language:string}){await publicDatabase()`select app.update_agent_profile(${actor.authUserId},${actor.providerSessionId},${actor.digest},${input.id},${input.revision},${input.name},${input.phone||null},${input.language})`;}
export async function setAgentStatus(actor:ApplicationUser,input:{id:string;revision:number;status:string;reason:string}){await publicDatabase()`select app.set_agent_status(${actor.authUserId},${actor.providerSessionId},${actor.digest},${input.id},${input.revision},${input.status},${input.reason})`;}
export async function recordSecurityAction(actor:ApplicationUser,id:string,action:string,revision:number){await publicDatabase()`select app.record_staff_security_action(${actor.authUserId},${actor.providerSessionId},${actor.digest},${id},${action},${revision})`;}
export async function completeStaffEmailChange(actor:ApplicationUser){await publicDatabase()`select app.complete_staff_email_change(${actor.authUserId},${actor.providerSessionId},${actor.digest})`;}
